export const VERSION=2;

export const WORKOUTS={
  split:{name:'保加利亚分腿蹲',en:'BULGARIAN SPLIT SQUAT',explain:'后脚垫高，前腿单独蹲；练腿，也练得更稳。',main:'strength',load:3},
  animal:{name:'Animal Flow / 动物流',en:'ANIMAL FLOW',explain:'手脚撑地连续移动；像动物，也要控制呼吸。',main:'mobility',load:2},
  prisoner:{name:'囚徒健身组合',en:'PRISONER CONDITIONING',explain:'用深蹲、俯卧撑和悬垂，把自身体重当器械。',main:'cardio',load:3},
  rdl:{name:'罗马尼亚硬拉',en:'ROMANIAN DEADLIFT',explain:'膝盖微屈、髋往后送；主要练臀和大腿后侧。',main:'strength',load:3},
  carry:{name:'农夫行走',en:'FARMER CARRY',explain:'两手提重物稳稳走；像拎菜，但身体不要歪。',main:'strength',load:2},
  run:{name:'坡度节奏跑',en:'INCLINE TEMPO RUN',explain:'在缓坡上控制步频；能说短句，但不会太轻松。',main:'cardio',load:3},
  crawl:{name:'熊爬与侧向穿越',en:'BEAR CRAWL',explain:'手脚着地低位移动；让肩、髋和核心一起工作。',main:'mobility',load:2}
};

export const SCHEDULE=[
  ['split','animal','prisoner'],['rdl','crawl','run'],['carry','animal','prisoner'],
  ['split','run','crawl'],['rdl','animal','prisoner'],['carry','run','crawl'],['split','animal','carry']
];

const WARMUPS=[
  [{id:'ankle',label:'先活动脚踝，再慢慢蹲下去',line:'你们扶着墙转脚踝。有人转得像在搅汤。',delta:{mobility:1,recovery:1}},{id:'race',label:'边聊天边走两圈',line:'第二圈时，呼吸终于和脚步站到同一边。',delta:{cardio:1,sync:1}}],
  [{id:'hinge',label:'拿木棍练髋部折叠',line:'木棍没有重量，但很擅长指出问题。',delta:{strength:1,recovery:1}},{id:'shake',label:'先把昨晚的困意甩掉',line:'大家甩了甩胳膊，像三件等待晾干的衣服。',delta:{sync:1,recovery:1}}],
  [{id:'floor',label:'从地面动作开始',line:'掌心贴地以后，身体慢慢醒了。',delta:{mobility:1,recovery:1}},{id:'music',label:'跟着店里的鼓点热身',line:'谁也没承认自己踩错过拍。',delta:{cardio:1,sync:1}}],
  [{id:'band',label:'用弹力带叫醒肩膀',line:'弹力带发出轻响，像在替你们打考勤。',delta:{strength:1,recovery:1}},{id:'walk',label:'去窗边来回快走',line:'玻璃里的几个人，看起来已经很像固定班底。',delta:{cardio:1,sync:1}}],
  [{id:'slow',label:'每个动作都慢一点',line:'慢下来之后，小晃动反而无处可藏。',delta:{mobility:1,recovery:1}},{id:'call',label:'轮流报下一个动作',line:'有人把“开合跳”报成了“开会跳”。',delta:{sync:2}}],
  [{id:'breath',label:'先找呼吸，不抢速度',line:'第一口完整的呼吸，让肩膀终于放了下来。',delta:{cardio:1,recovery:1}},{id:'mirror',label:'两个人互相看动作',line:'纠正动作时，大家使用了罕见的温和语气。',delta:{sync:2}}],
  [{id:'usual',label:'照这一周熟悉的顺序来',line:'没人再问下一步是什么。身体已经记住了。',delta:{recovery:1,sync:1}},{id:'free',label:'每个人选自己最需要的',line:'路线不同，但最后都在同一块垫子旁集合。',delta:{mobility:1,recovery:1}}]
];

const EVENTS=[
  {who:'巡场教练',text:'“第一次来？器械会用吗？”',choices:[{id:'ask',label:'承认有几个动作想确认',line:'教练把重量调轻一格：“会问，比会装熟强。”',delta:{recovery:2,sync:1}},{id:'show',label:'先做一遍空手版本',line:'你们认真演示了没有重量的重量训练。',delta:{mobility:1,sync:1}}]},
  {who:'储物柜',text:'最下层传来一声闷响。',choices:[{id:'look',label:'蹲下看看',line:'一只滚筒掉出来。没有怪物，只有泡沫轴。',delta:{recovery:2}},{id:'friend',label:'让旁边的人先开',line:'对方白了你一眼，还是一起蹲了下来。',delta:{sync:2}}]},
  {who:'陌生会员',text:'“这个动作到底练哪里？”',choices:[{id:'plain',label:'不用缩写，讲人话',line:'解释完以后，对方点头，你自己也更明白了。',delta:{mobility:1,sync:1}},{id:'demo',label:'做一个轻重量示范',line:'示范结束，队友很小声地鼓了掌。',delta:{strength:1,sync:1}}]},
  {who:'音响',text:'突然播了一首过分激昂的歌。',choices:[{id:'beat',label:'承认节奏确实有用',line:'大家默默踩上同一个拍子。',delta:{cardio:1,sync:2}},{id:'quiet',label:'把声音调小，听呼吸',line:'场地安静下来，只剩器械偶尔发表意见。',delta:{recovery:2}}]},
  {who:'饮水机',text:'纸杯只剩最后一个。',choices:[{id:'share',label:'拿自己的水壶分着倒',line:'杯子没少，洁癖边界也守住了。',delta:{sync:2}},{id:'buy',label:'下楼买几瓶新的',line:'回来时，多带了一瓶给前台。',delta:{recovery:1,sync:1}}]},
  {who:'窗外',text:'雨把整座城的速度调慢了。',choices:[{id:'stay',label:'今天就留在这里慢慢练',line:'雨声替你们数着组间休息。',delta:{recovery:2}},{id:'watch',label:'靠窗做完这一组',line:'玻璃上的倒影，动作比第一天整齐。',delta:{sync:2}}]},
  {who:'57training 前台',text:'“一周了。今天还照旧？”',choices:[{id:'same',label:'照旧，但谁都别逞强',line:'这句话已经像你们的队训。',delta:{recovery:2,sync:1}},{id:'photo',label:'先拍一张很糊的合照',line:'照片里没人站好，但每个人都在。',delta:{sync:3}}]}
];

export const APPEARANCE={
  hair:['短碎发','蓬松卷发','齐肩直发','高马尾','寸头','双丸子'],hairColor:['夜黑','栗棕','雾银','莓红','湖蓝'],eyes:['深棕','灰蓝','琥珀','墨绿'],
  top:['宽松 T 恤','短款卫衣','运动背心','薄夹克','网球衫'],bottom:['工装长裤','运动短裤','百褶裙','宽松长裙','束脚裤'],shoes:['旧跑鞋','高帮帆布鞋','训练鞋','厚底运动鞋'],accessory:['没有配件','圆框眼镜','发带','耳饰','棒球帽','彩色腕带'],body:['轻巧','修长','结实','圆润']
};
const NAMES=['小岚','诺亚','桃井','鹿文','阿满','乔安','小海','木木','迟夏','冬青'];
const RELATIONS=['常约饭的朋友','同事兼训练搭子','认识很久的网友','住在附近的人','关系有点微妙的人'];
const PRESETS=[
  {name:'小岚',relation:'常约饭的朋友',focus:'mobility',look:{hair:2,hairColor:3,eyes:0,top:2,bottom:3,shoes:1,accessory:3,body:0}},
  {name:'诺亚',relation:'同事兼训练搭子',focus:'strength',look:{hair:4,hairColor:2,eyes:1,top:0,bottom:0,shoes:2,accessory:1,body:2}},
  {name:'桃井',relation:'认识很久的网友',focus:'cardio',look:{hair:5,hairColor:4,eyes:2,top:1,bottom:2,shoes:3,accessory:5,body:1}},
  {name:'鹿文',relation:'关系有点微妙的人',focus:'balanced',look:{hair:1,hairColor:0,eyes:3,top:3,bottom:4,shoes:0,accessory:4,body:3}}
];

export function hash(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function randomSeed(){return (Date.now()^Math.floor(Math.random()*0xffffffff))>>>0}
export function defaultLook(seed=1,index=0){const look={};for(const [key,values] of Object.entries(APPEARANCE))look[key]=hash(`${seed}:${index}:${key}`)%values.length;return look}
function baseStats(focus,points){if(points&&points.length===3&&points.every(Number.isFinite))return {strength:points[0],cardio:points[1],mobility:points[2]};return {strength:focus==='strength'?4:focus==='balanced'?2:1,cardio:focus==='cardio'?4:focus==='balanced'?2:1,mobility:focus==='mobility'?4:focus==='balanced'?2:1}}
export function createCharacter(seed,index,spec={}){const focus=spec.focus||['balanced','strength','cardio','mobility'][hash(`${seed}:focus:${index}`)%4],base=baseStats(focus,spec.points);return {id:`p${index}`,name:String(spec.name||NAMES[hash(`${seed}:name:${index}`)%NAMES.length]).slice(0,10),relation:spec.relation||RELATIONS[hash(`${seed}:relation:${index}`)%RELATIONS.length],height:Number(spec.height)||165,weight:Number(spec.weight)||60,look:{...defaultLook(seed,index),...(spec.look||{})},hidden:{...base,fatigue:0,recovery:3,sync:0,proficiency:{},meals:{},sessions:[]},appearanceMark:null}}
export function presetContacts(seed){return PRESETS.map((p,i)=>createCharacter(seed,i+1,p))}
export function randomFriend(seed,index=1){return createCharacter(seed,index,{name:NAMES[hash(`${seed}:random:${index}`)%NAMES.length],relation:RELATIONS[hash(`${seed}:rel:${index}`)%RELATIONS.length]})}
export function createGame(seed,specs){const party=specs.slice(0,3).map((spec,i)=>createCharacter(seed,i,spec));if(!party.length)throw new Error('A player is required');return {version:VERSION,seed,day:1,step:'warmup',party,history:[],last:null}}
export function eventFor(seed,day){return EVENTS[(hash(`${seed}:event:${day}`)+day-1)%EVENTS.length]}
function applyDelta(party,delta){return party.map(p=>{const h={...p.hidden};for(const [key,value] of Object.entries(delta||{}))h[key]=(h[key]||0)+value;h.fatigue=Math.max(0,h.fatigue-(delta?.recovery||0));return {...p,hidden:h}})}
export function chooseWarmup(state,id){if(state.step!=='warmup')return state;const choice=WARMUPS[state.day-1]?.find(x=>x.id===id);if(!choice)return state;return {...state,step:'warmupResult',party:applyDelta(state.party,choice.delta),last:{kind:'warmup',line:choice.line,id}}}
export function continueToEvent(state){return state.step==='warmupResult'?{...state,step:'event'}:state}
export function chooseEvent(state,id){if(state.step!=='event')return state;const choice=eventFor(state.seed,state.day).choices.find(x=>x.id===id);if(!choice)return state;return {...state,step:'eventResult',party:applyDelta(state.party,choice.delta),last:{kind:'event',line:choice.line,id}}}
export function continueToWorkout(state){return state.step==='eventResult'?{...state,step:'workout'}:state}
export function doWorkout(state,id){if(state.step!=='workout'||!SCHEDULE[state.day-1]?.includes(id))return state;const workout=WORKOUTS[id];const party=state.party.map((p,index)=>{const h={...p.hidden,proficiency:{...p.hidden.proficiency},sessions:[...p.hidden.sessions,id]},aptitude=h[workout.main];h[workout.main]+=1;h.fatigue+=Math.max(1,workout.load-Math.floor((aptitude+h.recovery)/4));h.recovery=Math.max(0,h.recovery-1);h.sync+=state.party.length>1?1:0;h.proficiency[id]=(h.proficiency[id]||0)+1+(index===0?1:0);return {...p,hidden:h}});const tired=party[0].hidden.fatigue>=5,line=tired?'最后两次，你把动作换成了更稳妥的版本。教练点了点头。':'最后一次落地很稳。旁边的人替你记住了这个感觉。';return {...state,step:'watch',party,last:{kind:'workout',id,line}}}
export function chooseMeal(state,id){if(state.step!=='meal'||!['rice','noodles','soup'].includes(id))return state;const lines={rice:'热饭上桌以后，刚才还在逞强的人突然都安静了。',noodles:'第一口面太烫。大家吹了半天，像在做另一种呼吸训练。',soup:'汤端上来时，57store 的玻璃已经蒙了一层雾。'};const party=state.party.map(p=>{const h={...p.hidden,meals:{...p.hidden.meals}};h.meals[id]=(h.meals[id]||0)+1;h.fatigue=Math.max(0,h.fatigue-2);h.recovery+=id==='soup'?2:1;return {...p,hidden:h}});return {...state,step:'mealResult',party,last:{kind:'meal',id,line:lines[id]}}}
export function continueAfterMeal(state){if(state.step!=='mealResult')return state;return {...state,step:'summary',history:[...state.history,{day:state.day,workout:state.party[0].hidden.sessions.at(-1),meal:state.last.id}]}}
export function advanceDay(state){if(state.step!=='summary')return state;if(state.day===7){const party=state.party.map(p=>({...p,appearanceMark:appearanceRoute(p)}));return {...state,step:'weekEnding',party}}return {...state,day:state.day+1,step:'warmup',last:null}}
export function appearanceRoute(character){const h=character.hidden,counts={};for(const id of h.sessions)counts[WORKOUTS[id].main]=(counts[WORKOUTS[id].main]||0)+1;const meals=Object.values(h.meals).reduce((a,b)=>a+b,0),entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);if(meals>=6&&new Set(Object.keys(h.meals)).size>=3)return'store';if((counts.strength||0)>=Math.max(counts.cardio||0,counts.mobility||0))return'power';if((counts.mobility||0)>=(counts.cardio||0))return'flow';return'runner'}
export function endingText(route,name){return ({power:`${name}换衣服时，发现袖口比一周前紧了。再抬手，T 恤干脆变成了很有主张的背心。`,flow:`${name}站着系鞋带，身体顺手折成了一个过分流畅的角度。宽松下装似乎终于理解了这份工作。`,runner:`${name}下楼买水，走到街口才发现自己一直在控制呼吸。发带和轻装已经自动进入值班状态。`,store:`57store 店员把袋子递给${name}：“还是老样子？”这一周别的不说，熟客造型已经完全成立。`})[route]}

const hasDOM=typeof document!=='undefined';
if(hasDOM){
  const $=id=>document.getElementById(id);let seed=randomSeed(),screen='intro',gameState=null,animating=false,frame=0,raf=0,pendingAction='',dialogueRun=0;const trainingStart=new Date();trainingStart.setHours(12,0,0,0);
  const card={name:'',height:'168',weight:'60',points:[2,2,2],look:defaultLook(seed,0)};
  let contacts=presetContacts(seed),selected=[],custom=null;const scrollPositions={look:0,phone:0};
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button=(act,label,attrs='')=>`<button type="button" class="choice" data-act="${esc(act)}" ${attrs}>${label}</button>`;
  const stage=(label,place,body)=>`<section class="screen"><div class="stage-shell"><canvas class="stage" id="stage" width="240" height="160" aria-label="${esc(place)}的复古像素场景"></canvas><span class="stage-label">${esc(label)}</span><span class="stage-place">${esc(place)}</span>${watchHud()}<i class="scanlines"></i></div>${body}</section>`;
  const box=(speaker,content,classes='')=>`<div class="box${classes?' '+classes:''}"><div class="speaker">${esc(speaker)}</div>${content}</div>`;
  const option=(act,label)=>`<button type="button" class="choice select-option" data-act="selectChoice" data-choice="${esc(act)}" aria-pressed="false">${label}</button>`;
  const selection=(items,classes='',footer='')=>`<div class="dialogue-actions" hidden><div class="choices${classes?' '+classes:''}">${items.map(item=>option(item.act,item.label)).join('')}</div>${footer}<button type="button" class="choice confirm-choice" data-act="confirmChoice" disabled>确定</button></div>`;
  const delayedAction=content=>`<div class="dialogue-actions next" hidden>${content}</div>`;
  function announce(text){$('announcement').textContent=text}
  function currentParty(){return gameState?.party||[createCharacter(seed,0,{name:card.name||'你',height:card.height,weight:card.weight,points:card.points,look:card.look}),...selected.map(id=>contacts.find(x=>x.id===id)).filter(Boolean),...(custom?[custom]:[])].slice(0,3)}
  function sceneName(){if(screen==='card'||screen==='points')return'card';if(screen==='look')return'locker';if(screen==='phone')return'phone';if(!gameState)return'bedroom';if(gameState.step==='meal'||gameState.step==='mealResult')return'store';if(gameState.step==='summary'||gameState.step==='weekEnding')return'room';return'gym'}
  function gameDate(day=1){const date=new Date(trainingStart);date.setDate(trainingStart.getDate()+day-1);return `${date.getMonth()+1}/${date.getDate()}`}
  function watchTime(){return ({warmup:'07:38',warmupResult:'07:46',event:'07:49',eventResult:'07:55',workout:'08:03',watch:'08:47',meal:'09:02',mealResult:'09:18',summary:'22:16',weekEnding:'22:29'})[gameState?.step]||'07:24'}
  function watchHud(){if(!gameState)return'';const h=gameState.party[0].hidden,metrics=[['PWR',h.strength],['END',h.cardio],['MOB',h.mobility],['FAT',h.fatigue]],date=gameDate(gameState.day),time=watchTime();return `<aside class="sport-watch${gameState.step==='watch'?' is-updating':''}" aria-label="运动手表：${date}，${time}，${metrics.map(([label,value])=>`${label} ${value}`).join('，')}"><span class="watch-strap watch-strap-top" aria-hidden="true"></span><span class="watch-strap watch-strap-bottom" aria-hidden="true"></span><div class="watch-top"><span class="watch-date">${date}</span><strong class="watch-time">${time}</strong><span class="watch-icons" aria-hidden="true">▮▮▰</span><button type="button" class="watch-help" data-act="watchHelp" aria-expanded="false" aria-controls="watchLegend" aria-label="解释手表参数">?</button></div><div class="watch-metrics">${metrics.map(([label,value])=>`<span class="watch-metric"><span>${label}</span><strong>${String(Math.max(0,Math.round(value))).padStart(2,'0')}</strong></span>`).join('')}</div><div class="watch-legend" id="watchLegend" hidden><span><b>PWR</b> 发力</span><span><b>END</b> 续航</span><span><b>MOB</b> 活动</span><span><b>FAT</b> 疲劳</span></div></aside>`}
  function wheel(id,value,min,max,label){return `<input class="native-wheel-value" id="${id}" type="number" min="${min}" max="${max}" value="${esc(value)}" tabindex="-1" aria-hidden="true"><div class="number-wheel" role="listbox" tabindex="0" data-input="${id}" data-min="${min}" data-max="${max}" aria-label="${label}">${Array.from({length:max-min+1},(_,i)=>`<div class="number-wheel-item" id="${id}-${min+i}" role="option" data-value="${min+i}" aria-selected="false">${min+i}</div>`).join('')}</div>`}
  function render(){$('dayChip').textContent=gameState?gameDate(gameState.day):'DAY 0';pendingAction='';dialogueRun++;if(!gameState){if(screen==='intro')renderIntro();else if(screen==='card')renderCard();else if(screen==='points')renderPoints();else if(screen==='look')renderLook();else renderPhone()}else renderDay();initWheels();restoreScroll();startDialogue();cancelAnimationFrame(raf);frame=0;drawLoop();paintMinis()}
  function renderIntro(){$('game').innerHTML=stage('WEEK 01 / 07:12','你的房间',box('旁白','<h1>飙肌野郎</h1><p class="lead">手机震了一下。<br>57training 的七日体验卡，今天生效。</p>'+button('card','拿出健身卡')))}
  function renderCard(){$('game').innerHTML=stage('DAY 0 / CHECK IN','桌面',box('健身卡','<p>卡片边缘有点粗糙，正面只留了三行空白。</p><div class="form-grid"><label class="field">名字<input id="cardName" maxlength="10" autocomplete="off" value="'+esc(card.name)+'" placeholder="怎么称呼你"></label><label class="field">身高 / cm'+wheel('cardHeight',card.height,120,220,'身高，厘米')+'</label><label class="field">体重 / kg'+wheel('cardWeight',card.weight,30,220,'体重，公斤')+'</label></div><p class="privacy">资料只用于本次游戏，不上传、不保存，刷新/关闭后清除。</p>'+button('points','在卡背面盖下初始点数')))}
  function renderPoints(){const labels=[['发力感','想更稳地抬起东西'],['续航感','想让呼吸别那么快乱'],['活动感','想让身体更听话']],sum=card.points.reduce((a,b)=>a+b,0);$('game').innerHTML=stage('DAY 0 / CARD BACK','桌面',box(card.name||'你','<p>卡背面写着：<br>“六枚印章，盖在你想开始的地方。”</p><div class="points">'+labels.map((x,i)=>`<div class="point-row"><span>${x[0]}<small>${x[1]}</small></span><span class="point-controls"><button data-act="point-" data-index="${i}" aria-label="减少${x[0]}">−</button><output>${'◆'.repeat(card.points[i])}</output><button data-act="point+" data-index="${i}" aria-label="增加${x[0]}">＋</button></span></div>`).join('')+'</div><p class="point-note">还剩 '+(6-sum)+' 枚</p>'+button('look','去衣柜前看看',sum===6?'':'disabled')))}
  function lookRows(){return Object.entries(APPEARANCE).map(([key,values])=>`<div class="look-row"><button data-act="look-" data-key="${key}" aria-label="上一个选项">‹</button><span class="look-value">${esc(values[card.look[key]])}</span><button data-act="look+" data-key="${key}" aria-label="下一个选项">›</button></div>`).join('')}
  function renderLook(){$('game').innerHTML=stage('DAY 0 / GET DRESSED','衣柜',box(card.name||'你','<p>先穿得像自己。以后会变成什么样，等练完再说。</p><div class="scroll-area" data-scroll-key="look"><div class="look-grid">'+lookRows()+'</div></div><div class="panel-action">'+button('phone','衣服没问题，拿起手机')+'</div>','fixed-panel'))}
  function renderPhone(){const chosen=selected.length+(custom?1:0);$('game').innerHTML=stage('DAY 0 / 07:24','像素手机',box('你','<p class="lead">叫个人一起？</p><p class="phone-note">先选择联系人，最后统一发送。最多叫两个人；不选也可以自己去。</p><div class="scroll-area" data-scroll-key="phone"><div class="contact-list">'+contacts.map(p=>`<button class="contact" data-act="contact" data-id="${p.id}" aria-pressed="${selected.includes(p.id)}"><canvas class="mini-sprite" width="16" height="16" data-mini="${p.id}"></canvas><span><b>${esc(p.name)}</b><small>${esc(p.relation)}</small></span><span class="tick">${selected.includes(p.id)?'✓':'·'}</span></button>`).join('')+'</div>'+(custom?customFriendForm():button('addFriend','＋ 新建联系人 / 随机生成'))+`</div><p class="party-line panel-foot">${chosen?`已选择 <strong>${[...selected.map(id=>contacts.find(x=>x.id===id)?.name),custom?.name].filter(Boolean).join('、')}</strong>`:'还没有选择联系人。自己去也完全说得通。'}</p><div class="panel-action">`+button('startDay',chosen?'确认联系人并出发':'收起手机，自己出发')+'</div>','fixed-panel'))}
  function customFriendForm(){const labels=['发力','续航','活动'];return `<div class="custom-friend"><div class="form-grid"><label class="field">联系人名字<input id="friendName" maxlength="10" value="${esc(custom.name)}"></label><label class="field">你们的关系<input id="friendRelation" maxlength="16" value="${esc(custom.relation)}"></label></div><p class="phone-note">朋友的六枚初始印章，也可以自己分。</p><div class="custom-points">${labels.map((label,i)=>`<div class="point-row"><span>${label}</span><span class="point-controls"><button data-act="friendPoint-" data-index="${i}" aria-label="减少${label}">−</button><output>${custom._points[i]}</output><button data-act="friendPoint+" data-index="${i}" aria-label="增加${label}">＋</button></span></div>`).join('')}</div><div class="custom-focus"><button data-act="friendRandom">整个人随机</button><button data-act="friendRemove">移除联系人</button></div></div>`}
  function renderDay(){const s=gameState.step,day=gameState.day,party=gameState.party,names=party.map(p=>p.name).join('、');let html='';
    if(s==='warmup'){const choices=WARMUPS[day-1];html=box(day===1?'57training 前台':'训练搭子',`<p class="lead" data-dialogue>${day===1?'“卡给我。先别急着练。”':'“今天先怎么热身？”'}</p>${selection(choices.map(c=>({act:`warm:${c.id}`,label:esc(c.label)})),'',`<p class="party-line">今天到场：<strong>${esc(names)}</strong></p>`)}`)}
    else if(s==='warmupResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('toEvent','活动开了。往里走。'))}`);
    else if(s==='event'){const e=eventFor(gameState.seed,day);html=box(e.who,`<p class="lead" data-dialogue>${esc(e.text)}</p>${selection(e.choices.map(c=>({act:`event:${c.id}`,label:esc(c.label)})))}`)}
    else if(s==='eventResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('toWorkout','该正式练了'))}`);
    else if(s==='workout')html=box('巡场教练',`<p class="lead" data-dialogue>“今天三选一。名字不熟没关系，我说人话。”</p>${selection(SCHEDULE[day-1].map(id=>{const w=WORKOUTS[id];return {act:`work:${id}`,label:`<b>${esc(w.name)}</b><span>${esc(w.explain)}</span>`}}),'workout-list')}`);
    else if(s==='watch')html=box(party[0].name,`<p class="watch-copy" data-dialogue>你抬起手腕。表盘在像素画右下角闪了两下。</p><p data-dialogue>“${esc(gameState.last.line)}”</p>${delayedAction(button('toStore','去 57store 吃点东西'))}`);
    else if(s==='meal')html=box('57store 店员',`<p class="lead" data-dialogue>“练完了？今天吃什么？”</p>${selection([{act:'meal:rice',label:'照烧鸡肉饭和一份青菜'},{act:'meal:noodles',label:'热汤面，再加一个蛋'},{act:'meal:soup',label:'杂蔬汤、饭团和酸奶'}])}`);
    else if(s==='mealResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('afterMeal','把最后一口吃完'))}`);
    else if(s==='summary')html=box(party[0].name,`<div class="day-end"><p>洗完澡以后，今天的动作还留在身体里。</p><p>不是数字。只是下楼时，脚步比早上稳了一点。</p></div>${button('nextDay',day===7?'这一周，结束了':'睡一觉，进入 DAY '+(day+1))}`);
    else {const p=party[0],route=p.appearanceMark;html=box('镜子',`<p class="lead">${esc(endingText(route,p.name))}</p><p>没有弹窗，也没有谁宣布升级。只是镜子里的你，确实留下了一点这一周的样子。</p><div class="credits">WEEK 01 COMPLETE · 本次资料只留在当前运行内存中</div>${button('again','穿着这身，再来一周')}`)}
    const labels={warmup:'WARM UP',warmupResult:'2-FRAME MOTION',event:'EVENT',eventResult:'DIALOGUE',workout:'57TRAINING',watch:'WRIST WATCH',meal:'RECOVERY',mealResult:'57STORE',summary:'DAY END',weekEnding:'WEEK END'},scene=sceneName(),place=scene==='store'?'57store':scene==='gym'?'57training':scene==='watch'?'手腕':'你的房间';$('game').innerHTML=stage(`${gameDate(day)} / ${labels[s]}`,place,html)
  }
  function initWheels(){document.querySelectorAll('.number-wheel').forEach(wheel=>{const input=$(wheel.dataset.input),min=Number(wheel.dataset.min),max=Number(wheel.dataset.max),row=Number.parseFloat(getComputedStyle(wheel).getPropertyValue('--wheel-row'))||22;let selected=null,ticking=false;const sync=value=>{const next=Math.max(min,Math.min(max,value));if(selected)selected.setAttribute('aria-selected','false');selected=wheel.querySelector(`[data-value="${next}"]`);selected?.setAttribute('aria-selected','true');if(selected)wheel.setAttribute('aria-activedescendant',selected.id);if(input&&input.value!==String(next)){input.value=String(next);input.dispatchEvent(new Event('input',{bubbles:true}))}};const syncScroll=()=>sync(min+Math.round(wheel.scrollTop/row));wheel.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false;syncScroll()})});wheel.addEventListener('click',event=>{const item=event.target.closest('.number-wheel-item');if(item)wheel.scrollTo({top:(Number(item.dataset.value)-min)*row,behavior:'smooth'})});wheel.addEventListener('keydown',event=>{const keys={ArrowUp:-1,ArrowDown:1,PageUp:-5,PageDown:5};if(!(event.key in keys))return;event.preventDefault();const value=Math.max(min,Math.min(max,Number(input.value)+keys[event.key]));wheel.scrollTo({top:(value-min)*row,behavior:'smooth'});sync(value)});const value=Math.max(min,Math.min(max,Number(input?.value)||min));wheel.scrollTop=(value-min)*row;sync(value)})}
  function restoreScroll(){requestAnimationFrame(()=>document.querySelectorAll('.scroll-area[data-scroll-key]').forEach(area=>{area.scrollTop=scrollPositions[area.dataset.scrollKey]||0}))}
  function startDialogue(){const root=$('game'),lines=[...root.querySelectorAll('[data-dialogue]')],actions=root.querySelector('.dialogue-actions');if(!lines.length||!actions)return;const run=dialogueRun,reduce=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;const reveal=()=>{if(run!==dialogueRun)return;actions.hidden=false;actions.classList.add('is-ready');announce('选项已出现')};if(reduce){reveal();return}const full=lines.map(line=>line.textContent);lines.forEach(line=>line.textContent='');let lineIndex=0,charIndex=0;const tick=()=>{if(run!==dialogueRun)return;const line=lines[lineIndex],text=full[lineIndex];if(charIndex<text.length){const char=text[charIndex++];line.textContent=text.slice(0,charIndex);setTimeout(tick,/[。！？…，；：]/.test(char)?72:28);return}lineIndex++;charIndex=0;if(lineIndex<lines.length){setTimeout(tick,110);return}setTimeout(reveal,220)};setTimeout(tick,70)}
  function saveInputs(){const n=$('cardName'),h=$('cardHeight'),w=$('cardWeight');if(n)card.name=n.value;if(h)card.height=h.value;if(w)card.weight=w.value;const fn=$('friendName'),fr=$('friendRelation');if(custom&&fn){custom.name=fn.value||custom.name;custom.relation=fr.value||custom.relation}}
  function startAnimation(next,ms=1050){animating=true;$('game').querySelectorAll('button').forEach(b=>b.disabled=true);setTimeout(()=>{animating=false;next();render()},ms)}
  document.addEventListener('input',saveInputs);
  document.addEventListener('scroll',event=>{const area=event.target.closest?.('.scroll-area[data-scroll-key]');if(area)scrollPositions[area.dataset.scrollKey]=area.scrollTop},true);
  document.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b||b.disabled||animating)return;saveInputs();let a=b.dataset.act;
    if(a==='watchHelp'){const watch=b.closest('.sport-watch'),legend=watch?.querySelector('.watch-legend'),open=Boolean(legend?.hidden);if(legend)legend.hidden=!open;b.setAttribute('aria-expanded',String(open));return}
    if(a==='selectChoice'){const panel=b.closest('.dialogue-actions');panel?.querySelectorAll('.select-option').forEach(choice=>choice.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');pendingAction=b.dataset.choice||'';const confirmButton=panel?.querySelector('.confirm-choice');if(confirmButton)confirmButton.disabled=!pendingAction;announce('已选择：'+b.textContent.trim());return}
    if(a==='confirmChoice'){if(!pendingAction)return;a=pendingAction}
    if(a==='restart'){if(confirm('从 DAY 0 重新开始？本次进度会立即清除。'))location.reload();return}if(a==='card'||a==='points'||a==='look'||a==='phone'){screen=a;render();return}
    if(a==='point-'||a==='point+'){const i=Number(b.dataset.index),sum=card.points.reduce((x,y)=>x+y,0);if(a==='point-'&&card.points[i]>1)card.points[i]--;if(a==='point+'&&card.points[i]<4&&sum<6)card.points[i]++;render();return}
    if(a==='look-'||a==='look+'){const key=b.dataset.key,n=APPEARANCE[key].length;card.look[key]=(card.look[key]+(a==='look+'?1:-1)+n)%n;render();return}
    if(a==='contact'){const id=b.dataset.id;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length+(custom?1:0)<2)selected.push(id);else announce('最多邀请两个人');render();return}
    if(a==='addFriend'){if(selected.length>=2){announce('队伍已经有三个人了');return}custom=randomFriend(seed,3);custom._points=[2,2,2];render();return}if(a==='friendRandom'){const nextSeed=randomSeed();custom=randomFriend(nextSeed,3);custom._points=[1,1,1];for(let n=0;n<3;n++){let i=hash(`${nextSeed}:point:${n}`)%3;while(custom._points[i]>=4)i=(i+1)%3;custom._points[i]++}render();return}if(a==='friendRemove'){custom=null;render();return}
    if(a==='friendPoint-'||a==='friendPoint+'){const i=Number(b.dataset.index),sum=custom._points.reduce((x,y)=>x+y,0);if(a==='friendPoint-'&&custom._points[i]>1)custom._points[i]--;if(a==='friendPoint+'&&custom._points[i]<4&&sum<6)custom._points[i]++;render();return}
    if(a==='startDay'){const self={name:card.name.trim()||'阿野',height:card.height,weight:card.weight,points:card.points,look:card.look,relation:'你自己'},specs=[self,...selected.map(id=>{const p=contacts.find(x=>x.id===id);return {name:p.name,relation:p.relation,look:p.look,focus:dominantFocus(p)}}),...(custom?[{name:custom.name,relation:custom.relation,look:custom.look,points:custom._points}]:[])];gameState=createGame(seed,specs);screen='day';startAnimation(()=>{},850);return}
    if(a.startsWith('warm:')){startAnimation(()=>{gameState=chooseWarmup(gameState,a.slice(5))});return}if(a==='toEvent'){gameState=continueToEvent(gameState);render();return}if(a.startsWith('event:')){startAnimation(()=>{gameState=chooseEvent(gameState,a.slice(6))});return}if(a==='toWorkout'){gameState=continueToWorkout(gameState);render();return}if(a.startsWith('work:')){startAnimation(()=>{gameState=doWorkout(gameState,a.slice(5))},1400);return}if(a==='toStore'){gameState={...gameState,step:'meal'};render();return}if(a.startsWith('meal:')){gameState=chooseMeal(gameState,a.slice(5));render();return}if(a==='afterMeal'){gameState=continueAfterMeal(gameState);render();return}if(a==='nextDay'){gameState=advanceDay(gameState);render();return}
    if(a==='again'){const specs=gameState.party.map(p=>({name:p.name,relation:p.relation,look:p.look,focus:'balanced'}));seed=randomSeed();gameState=createGame(seed,specs);render()}
  });
  function dominantFocus(p){return ['strength','cardio','mobility'].sort((a,b)=>p.hidden[b]-p.hidden[a])[0]}
  function paintMinis(){document.querySelectorAll('[data-mini]').forEach(c=>{const p=contacts.find(x=>x.id===c.dataset.mini);if(p)drawMini(c.getContext('2d'),p,3,14,0,'idle',1)})}
  function drawLoop(){const canvas=$('stage');if(!canvas)return;drawScene(canvas.getContext('2d'),sceneName(),frame,currentParty());frame=(frame+1)%4;raf=requestAnimationFrame(()=>setTimeout(drawLoop,animating?170:520))}
  function rect(x,c,px,py,w,h){x.fillStyle=c;x.fillRect(px,py,w,h)}
  function drawMini(x,p,px,ground,f,action='idle',scale=2){const L=p.look||defaultLook(1,0),skin=['#f0c39b','#b97858','#8c533d','#f2d1b1'][(L.eyes+L.body)%4],hair=['#2b2531','#6c4438','#c7c6bd','#a33c58','#326b82'][L.hairColor%5],tops=['#e26d78','#697ab3','#f0c85c','#5d927b','#eee3bf'],bottoms=['#3d4265','#486967','#8f5e80','#d8a967','#333846'],shoe=['#eee3bf','#25283a','#b74b5a','#6d5d84'][L.shoes%4],bob=f%2&&action!=='watch'?scale:0,wide=p.appearanceMark==='power'?scale:0;rect(x,hair,px+3*scale,ground-13*scale+bob,4*scale,3*scale);if(L.hair===2||L.hair===3||L.hair===5)rect(x,hair,px+2*scale,ground-11*scale+bob,6*scale,5*scale);rect(x,skin,px+3*scale,ground-11*scale+bob,4*scale,4*scale);rect(x,tops[L.top%5],px+2*scale-wide,ground-7*scale+bob,6*scale+wide*2,5*scale);if(p.appearanceMark==='power')rect(x,skin,px,ground-6*scale+bob,2*scale,4*scale);else{rect(x,skin,px+scale,ground-6*scale+bob,scale,4*scale);rect(x,skin,px+8*scale,ground-6*scale+bob,scale,4*scale)}rect(x,bottoms[L.bottom%5],px+2*scale,ground-2*scale+bob,3*scale,3*scale);rect(x,bottoms[L.bottom%5],px+6*scale,ground-2*scale+bob,2*scale,3*scale);const step=f%2&&action!=='watch'?scale:0;rect(x,shoe,px+2*scale-step,ground+scale,3*scale,scale);rect(x,shoe,px+6*scale+step,ground+scale,3*scale,scale);if(L.accessory===1)rect(x,'#28304b',px+3*scale,ground-10*scale+bob,4*scale,scale);if(L.accessory===4||p.appearanceMark==='runner')rect(x,'#edc75e',px+2*scale,ground-12*scale+bob,6*scale,scale);if(action==='watch')rect(x,'#73c2bf',px+9*scale,ground-5*scale,2*scale,2*scale)}
  function drawScene(x,scene,f,party){x.imageSmoothingEnabled=false;x.clearRect(0,0,240,160);const sky=scene==='room'||scene==='bedroom'||scene==='locker'?'#65658a':'#8bc4b8';rect(x,sky,0,0,240,160);
    if(scene==='gym'){rect(x,'#d8e9c4',0,52,240,108);rect(x,'#59647a',0,118,240,42);for(let i=0;i<6;i++)rect(x,'#4b5368',i*44,118,2,42);rect(x,'#34384f',18,28,4,90);rect(x,'#34384f',20,28,52,4);rect(x,'#e56b88',180,66,34,4);rect(x,'#34384f',187,70,4,48);rect(x,'#34384f',207,70,4,48);party.forEach((p,i)=>drawMini(x,p,48+i*52,112,f,animating?'move':'idle',2))}
    else if(scene==='store'){rect(x,'#f2d59a',0,44,240,116);rect(x,'#87566d',0,116,240,44);rect(x,'#5c435c',15,24,65,76);for(let y=36;y<94;y+=18)rect(x,'#f4e3b2',20,y,55,5);rect(x,'#3b4156',112,74,108,8);rect(x,'#f3ca67',123,62,22,12);rect(x,'#75a765',155,60,18,14);party.forEach((p,i)=>drawMini(x,p,50+i*48,113,f,'idle',2))}
    else if(scene==='watch'){rect(x,'#27283d',0,0,240,160);rect(x,'#bd926e',46,70,148,34);rect(x,'#222538',92,45,58,72);rect(x,'#65c3bd',98,51,46,60);rect(x,'#1e2634',103,56,36,50);const dots=f%4+4;for(let i=0;i<dots;i++)rect(x,'#f3ca67',108+i*4,77,2,8);rect(x,'#f4edc7',111,93,25,3)}
    else if(scene==='phone'){rect(x,'#2b2b42',0,0,240,160);rect(x,'#151625',68,8,104,144);rect(x,'#d8e9c4',74,17,92,126);rect(x,'#5a6378',79,25,82,12);for(let i=0;i<4;i++){rect(x,'#fff',80,43+i*22,80,17);rect(x,['#e56b88','#65c3bd','#f3ca67','#75a765'][i],84,47+i*22,9,9)}rect(x,'#65c3bd',104,132,31,4)}
    else if(scene==='card'){rect(x,'#8c5e5b',0,0,240,160);rect(x,'#5b3f49',0,118,240,42);rect(x,'#f8f0c8',45,25,150,96);rect(x,'#e56b88',45,25,150,14);for(let i=0;i<4;i++)rect(x,'#636579',62,53+i*14,105,2);rect(x,'#65c3bd',159,94,20,14)}
    else {rect(x,'#444563',0,0,240,160);rect(x,'#25263a',0,110,240,50);rect(x,'#9f6a78',18,53,75,57);rect(x,'#f8f0c8',24,61,63,24);rect(x,'#34364f',145,26,68,84);for(let i=0;i<3;i++)rect(x,'#c7b76d',153+i*18,39,12,12);party.forEach((p,i)=>drawMini(x,p,65+i*48,108,f,'idle',2))}
  }
  render();
}
