import {installVariety,ARRIVALS,ENDING_LINES,MEAL_ARRIVALS,ABSENT_REASONS,MORE_MIRROR,MORE_MENU,MORE_REPLIES} from './variety.js?v=dx7';
import {NEW_CHARACTERS,NEW_FRIEND_ROWS,FRIEND_GROUPS,EXTRA_MENUS,SIDE_DISHES} from './expansion.js?v=dx7';
import {MIRROR_POOLS,GROUP_REPLIES,GROUP_ACK} from './narrative.js?v=dx7';
import {EXTRA_WORKOUTS,EXTRA_SCHEDULE,GYM_EXTRAS,NIGHT_EXTRAS,FRIEND_EVENTS,FRIEND_PHASES,makeFriendEvent} from './content.js?v=dx7';
export const VERSION=8;
export {FRIEND_EVENTS,FRIEND_PHASES,MIRROR_POOLS,GROUP_REPLIES,GYM_EXTRAS,NIGHT_EXTRAS,FRIEND_GROUPS};

export const WORKOUTS={...EXTRA_WORKOUTS,
  split:{name:'保加利亚分腿蹲',en:'BULGARIAN SPLIT SQUAT',explain:'后脚垫高，前腿单独蹲；练腿，也练得更稳。',main:'strength',load:3},
  animal:{name:'Animal Flow / 动物流',en:'ANIMAL FLOW',explain:'手脚撑地连续移动；像动物，也要控制呼吸。',main:'mobility',load:2},
  prisoner:{name:'囚徒健身组合',en:'PRISONER CONDITIONING',explain:'用深蹲、俯卧撑和悬垂，把自身体重当器械。',main:'cardio',load:3},
  rdl:{name:'罗马尼亚硬拉',en:'ROMANIAN DEADLIFT',explain:'膝盖微屈、髋往后送；主要练臀和大腿后侧。',main:'strength',load:3},
  carry:{name:'农夫行走',en:'FARMER CARRY',explain:'两手提重物稳稳走；像拎菜，但身体不要歪。',main:'strength',load:2},
  run:{name:'坡度节奏跑',en:'INCLINE TEMPO RUN',explain:'在缓坡上控制步频；能说短句，但不会太轻松。',main:'cardio',load:3},
  crawl:{name:'熊爬与侧向穿越',en:'BEAR CRAWL',explain:'手脚着地低位移动；让肩、髋和核心一起工作。',main:'mobility',load:2},
  press:{name:'半跪姿单臂推举',en:'HALF-KNEELING PRESS',explain:'单膝跪地向上推举；肩膀发力，躯干负责不乱晃。',main:'strength',load:2},
  row:{name:'坐姿划船',en:'SEATED ROW',explain:'把手柄拉向身体；背部工作，肩膀不要抢着耸起来。',main:'strength',load:2},
  bike:{name:'单车间歇',en:'BIKE INTERVAL',explain:'快慢交替踩车；腿会抗议，但呼吸仍要保持节奏。',main:'cardio',load:3},
  balance:{name:'单腿平衡序列',en:'BALANCE SERIES',explain:'单脚站立完成触地和转向；练的是控制，不是憋气。',main:'mobility',load:2}
};

export const SCHEDULE=[
  ['split','animal','prisoner'],['rdl','crawl','row'],['carry','animal','bike'],
  ['split','run','balance'],['rdl','press','prisoner'],['carry','bike','crawl'],['split','run','press','animal']
];

const WARMUPS=[
  [{id:'ankle',label:'先活动脚踝，再慢慢蹲下去',line:'你们扶着墙转脚踝。有人转得像在搅汤。',delta:{mobility:1,recovery:1}},{id:'race',label:'边聊天边走两圈',line:'第二圈时，呼吸终于和脚步站到同一边。',delta:{cardio:1,sync:1}}],
  [{id:'hinge',label:'拿木棍练髋部折叠',line:'木棍没有重量，但很擅长指出问题。',delta:{strength:1,recovery:1}},{id:'shake',label:'先把昨晚的困意甩掉',line:'大家甩了甩胳膊，像三件等待晾干的衣服。',delta:{sync:1,recovery:1}}],
  [{id:'floor',label:'从地面动作开始',line:'掌心贴地以后，身体慢慢醒了。',delta:{mobility:1,recovery:1}},{id:'music',label:'跟着店里的鼓点热身',line:'谁也没承认自己踩错过拍。',delta:{cardio:1,sync:1}}],
  [{id:'band',label:'用弹力带叫醒肩膀',line:'弹力带发出轻响，像在替你们打考勤。',delta:{strength:1,recovery:1}},{id:'walk',label:'去窗边来回快走',line:'玻璃里的几个人，看起来已经很像固定班底。',delta:{cardio:1,sync:1}}],
  [{id:'slow',label:'每个动作都慢一点',line:'慢下来之后，小晃动反而无处可藏。',delta:{mobility:1,recovery:1}},{id:'call',label:'轮流报下一个动作',line:'有人把“开合跳”报成了“开会跳”。',delta:{sync:2}}],
  [{id:'breath',label:'先找呼吸，不抢速度',line:'第一口完整的呼吸，让肩膀终于放了下来。',delta:{cardio:1,recovery:1}},{id:'mirror',label:'两个人互相看动作',line:'纠正动作时，大家使用了罕见的温和语气。',delta:{sync:2}}],
  [{id:'usual',label:'照这一周熟悉的顺序来',line:'没人再问下一步是什么。身体已经记住了。',delta:{recovery:1,sync:1}},{id:'free',label:'每个人选自己最需要的',line:'路线不同，但最后都在同一块垫子旁集合。',delta:{mobility:1,recovery:1}}]
];

const EVENT_POOLS=[[
  {who:'巡场教练',text:'“第一次来？器械会用吗？”',choices:[{id:'ask',label:'承认有几个动作想确认',line:'教练把重量调轻一格：“会问，比会装熟强。”',delta:{recovery:2,sync:1}},{id:'show',label:'先做一遍空手版本',line:'你们认真演示了没有重量的重量训练。',delta:{mobility:1,sync:1}}]},
  {who:'前台贴纸',text:'体验卡背面写着：“不舒服就停，尴尬不会扣分。”',choices:[{id:'keep',label:'把这句话记住',line:'你把面子暂时寄存在前台。',delta:{awareness:2}},{id:'joke',label:'拍给朋友看',line:'朋友回了一个“已为你保存证据”。',delta:{social:2}}]}
],[
  {who:'储物柜',text:'最下层传来一声闷响。',choices:[{id:'look',label:'蹲下看看',line:'一只滚筒掉出来。没有怪物，只有泡沫轴。',delta:{recovery:2,curiosity:1}},{id:'friend',label:'让旁边的人先开',line:'对方白了你一眼，还是一起蹲了下来。',delta:{sync:2,social:1}}]},
  {who:'昨日酸痛',text:'坐下时，昨天练过的地方抢先打了招呼。',choices:[{id:'listen',label:'今天避开它',line:'你第一次把“没硬撑”也算成完成。',delta:{awareness:2,recovery:2}},{id:'warm',label:'多热身一会再决定',line:'酸痛没有消失，但语气温和了一点。',delta:{discipline:2}}]}
],[
  {who:'陌生会员',text:'“这个动作到底练哪里？”',choices:[{id:'plain',label:'不用缩写，讲人话',line:'解释完以后，对方点头，你自己也更明白了。',delta:{mobility:1,sync:1}},{id:'demo',label:'做一个轻重量示范',line:'示范结束，队友很小声地鼓了掌。',delta:{strength:1,sync:1}}]},
  {who:'器械维修牌',text:'你计划用的器械今天暂时下班。',choices:[{id:'swap',label:'换一个相近动作',line:'计划改变了，训练没有因此失去法律效力。',delta:{adaptability:2}},{id:'wait',label:'等它附近的位置空出来',line:'你守住了计划，也目送三个人练完。',delta:{discipline:2,fatigue:1}}]}
],[
  {who:'音响',text:'突然播了一首过分激昂的歌。',choices:[{id:'beat',label:'承认节奏确实有用',line:'大家默默踩上同一个拍子。',delta:{cardio:1,sync:2}},{id:'quiet',label:'把声音调小，听呼吸',line:'场地安静下来，只剩器械偶尔发表意见。',delta:{recovery:2}}]},
  {who:'运动手表',text:'恢复提示今天格外乐观，像一个不了解你的新同事。',choices:[{id:'plus',label:'只多加一点',line:'那一点成功了，没有顺便带走动作。',delta:{risk:1,confidence:2}},{id:'normal',label:'照原计划',line:'状态很好，也不一定非要拿来证明什么。',delta:{discipline:2,awareness:1}}]}
],[
  {who:'饮水机',text:'纸杯只剩最后一个。',choices:[{id:'share',label:'拿自己的水壶分着倒',line:'杯子没少，洁癖边界也守住了。',delta:{sync:2}},{id:'buy',label:'下楼买几瓶新的',line:'回来时，多带了一瓶给前台。',delta:{recovery:1,sync:1}}]},
  {who:'训练搭子',text:'组间休息变成了临时饭局会议。',choices:[{id:'join',label:'认真参与选店',line:'你对社交没有意见，主要是对菜单很有意见。',delta:{social:2,curiosity:1}},{id:'timer',label:'先把下一组做完',line:'计时器响了，讨论暂时败给执行力。',delta:{discipline:2}}]}
],[
  {who:'窗外',text:'雨把整座城的速度调慢了。',choices:[{id:'stay',label:'今天就留在这里慢慢练',line:'雨声替你们数着组间休息。',delta:{recovery:2}},{id:'watch',label:'靠窗做完这一组',line:'玻璃上的倒影，动作比第一天整齐。',delta:{sync:2}}]},
  {who:'鞋带',text:'它在最不适合的时候松了第二次。',choices:[{id:'redo',label:'停下来重新系好',line:'这一分钟没有训练记录，但保住了后面的记录。',delta:{awareness:2}},{id:'double',label:'打一个极其认真的死结',line:'结很可靠。今晚脱鞋的问题交给今晚。',delta:{discipline:1,confidence:1}}]}
],[
  {who:'57training 前台',text:'“一周了。今天还照旧？”',choices:[{id:'same',label:'照旧，但谁都别逞强',line:'这句话已经像你们的队训。',delta:{recovery:2,sync:1}},{id:'photo',label:'先拍一张很糊的合照',line:'照片里没人站好，但每个人都在。',delta:{sync:3}}]}
]];

export const MENUS={
 'dx捕鲸堡':[{"id":"dx-classic","name":"招牌双层牛肉堡套餐","icon":"burger","price":32,"line":"纸包一展开，芝士先宣布今天值得庆祝。","delta":{"fuel":4,"mood":2}},{"id":"dx-chicken","name":"脆脆鸡腿堡套餐","icon":"burger","price":28,"line":"咔嚓一声。今晚最清楚的反馈来自面包中间。","delta":{"fuel":3,"mood":3}},{"id":"dx-fish","name":"深海鳕鱼堡","icon":"burger","price":25,"line":"名字把你带到海边，取餐号又把你叫回柜台。","delta":{"fuel":2,"recovery":2}},{"id":"dx-wrap","name":"烤鸡蔬菜卷","icon":"sandwich","price":24,"line":"卷饼很努力地维持秩序，生菜还是探出了头。","delta":{"fuel":2,"recovery":3}},{"id":"dx-nuggets","name":"金块鸡块分享盒","icon":"leg","price":29,"line":"盒子叫分享盒。你决定先看看桌上有几只手。","delta":{"fuel":3,"social":1,"mood":2}},{"id":"dx-breakfast","name":"全天早餐蛋堡","icon":"burger","price":20,"line":"已经是晚上了，鸡蛋对此没有时差。","delta":{"fuel":2,"thrift":1}},{"id":"dx-veggie","name":"蘑菇芝士堡","icon":"burger","price":26,"line":"蘑菇没有冒充牛肉，芝士也没要求它这么做。","delta":{"fuel":2,"recovery":2,"mood":1}},{"id":"dx-hot","name":"辣味鸡翅配玉米杯","icon":"leg","price":30,"line":"辣味来得很直接，玉米负责把谈话拉回正常音量。","delta":{"fuel":3,"mood":2}},{"id":"dx-small","name":"小汉堡薯条组合","icon":"burger","price":22,"line":"纸袋里装着一份大小合适的满足。","delta":{"fuel":2,"thrift":1,"mood":1}}],
  '向羽轩':[{id:'pepper',icon:'rice',name:'青椒肉丝盖饭',price:32,line:'辣味来得比预想认真，米饭负责维持谈判。',delta:{fuel:3,recovery:2,mood:2}},{id:'dumpling',icon:'dumpling',name:'饺子配酸辣汤',price:29,line:'最后一只饺子的归属，被大家礼貌地忽略了。',delta:{fuel:2,recovery:2,social:2}},{id:'tofu',icon:'tofu',name:'家常豆腐套餐',price:26,line:'豆腐比想象中烫。你获得了短暂而具体的耐心。',delta:{fuel:2,recovery:3}}],
  '日立屋':[{id:'beef',icon:'bowl',name:'牛肉饭',price:36,line:'酱汁把疲惫按回了碗底。',delta:{fuel:3,recovery:2}},{id:'egg',icon:'egg',name:'牛肉鸡蛋饭',price:43,line:'蛋黄破开的那一刻，今天突然显得没有那么难。',delta:{fuel:4,recovery:3,mood:1}},{id:'curry',icon:'curry',name:'咖喱饭',price:39,line:'第一口很可靠，第二口开始有点想加量。',delta:{fuel:3,mood:2,impulse:1}}],
  '飞飞小厨':[{id:'chicken',icon:'leg',name:'红烧鸡腿饭',price:38,line:'鸡腿很认真，你也决定认真把饭吃完。',delta:{fuel:3,recovery:3}},{id:'tomato',icon:'egg',name:'番茄炒蛋',price:25,line:'甜咸比例没有结论，但盘子很快空了。',delta:{fuel:2,mood:3}},{id:'fish',icon:'fish',name:'香煎鱼套餐',price:48,line:'鱼皮很脆。刚才那组失败突然不值得追究了。',delta:{fuel:3,recovery:4,mood:1}}],
  '熙兰拉面':[{id:'noodle',icon:'noodle',name:'牛肉拉面',price:35,line:'第一口面太烫，大家吹了半天，像另一种呼吸训练。',delta:{fuel:3,recovery:3}},{id:'soup',icon:'soup',name:'鸡汤面',price:32,line:'热汤下去以后，肩膀终于不再假装值班。',delta:{fuel:2,recovery:4}},{id:'deluxe',icon:'noodle',name:'加肉加蛋大盛',price:52,line:'碗比计划大一圈。计划决定尊重现实。',delta:{fuel:5,mood:2,impulse:2}}],
  '57store':[{id:'sandwich',icon:'sandwich',name:'火腿蛋三明治',price:16,line:'比想象中好吃。包装袋对此保持沉默。',delta:{fuel:2,discipline:1}},{id:'riceball',icon:'riceball',name:'金枪鱼饭团和酸奶',price:19,line:'饭团在三口之内结束，酸奶负责延长晚餐。',delta:{fuel:2,recovery:2}},{id:'bento',icon:'bento',name:'打折便当',price:22,line:'贴纸写着临期，味道写着今晚还行。',delta:{fuel:3,thrift:2}}],
  '几丁质功能饮料自动贩卖机':[{id:'sport',icon:'drink',name:'几丁质电解质饮料',price:12,line:'颜色很像系统警告，味道倒没有那么危险。',delta:{fuel:1,recovery:2,curiosity:2}},{id:'coffee',icon:'coffee',name:'黑咖啡',price:9,line:'困意暂时退场。它没有承诺今晚不回来。',delta:{fuel:2,sleep:-2,impulse:1}},{id:'mystery',icon:'mystery',name:'本周限定无标签饮料',price:15,line:'喝起来像青苹果和一次不必要的冒险。',delta:{fuel:2,mood:2,curiosity:3}}],
  '拾叁面包房':[{id:'bagel',icon:'bagel',name:'鸡肉贝果',price:24,line:'贝果很有嚼劲，今天的最后一组也是。',delta:{fuel:2,recovery:2}},{id:'redbean',icon:'bread',name:'红豆面包和牛奶',price:18,line:'甜味很老派，疲惫也跟着安静了一会。',delta:{fuel:2,mood:2}},{id:'currybread',icon:'bread',name:'咖喱面包',price:15,line:'馅料差点从另一边逃走。你及时挽救了晚餐。',delta:{fuel:2,curiosity:1}}]
};
const DAY_STORES=[['57store','日立屋','dx捕鲸堡'],['拾叁面包房','向羽轩'],['飞飞小厨','几丁质功能饮料自动贩卖机','dx捕鲸堡'],['熙兰拉面','日立屋'],['向羽轩','57store','飞飞小厨'],['几丁质功能饮料自动贩卖机','拾叁面包房'],['熙兰拉面','飞飞小厨','57store','dx捕鲸堡']];
export function storesFor(seed,day,state){const stores=DAY_STORES[day-1].slice();if(state?.party.some(p=>p.profile?.preferredStores?.includes('dx捕鲸堡'))&&!stores.includes('dx捕鲸堡'))stores.push('dx捕鲸堡');const offset=hash(`${seed}:stores:${day}`)%stores.length;return stores.slice(offset).concat(stores.slice(0,offset))}
const STORE_LINES={'dx捕鲸堡':'店员指指亮着的菜单：“套餐不用表决，饮料口味可以再想想。”','向羽轩':'店员把菜单推过来：“今天练腿？那坐稳了再点。”','日立屋':'店员抬头：“又是训练完？这次还加蛋吗？”','飞飞小厨':'店长从出餐口探头：“先说好，算恢复餐，不算放纵餐。”','熙兰拉面':'拉面师傅把漏勺一甩：“面量可以选，明天的酸痛不可以。”','57store':'夜班店员扫了眼你的运动包：“微波炉右边那台比较有耐心。”','几丁质功能饮料自动贩卖机':'屏幕亮起一行字：请选择你愿意相信的颜色。','拾叁面包房':'面包师傅夹起最后一个贝果：“你来得正好，它也快下班了。”'};
const STORE_ARRIVALS={'dx捕鲸堡':'红黄灯箱亮着，取餐声从玻璃门里传出来。纸袋的香味比促销标语更有说服力。','向羽轩':'招牌亮着。隔着玻璃，锅铲正在处理今晚最后几份耐心。','日立屋':'纸灯箱有一点歪，但牛肉饭的气味方向非常准确。','飞飞小厨':'出餐口传来一声“马上好”，听起来至少还需要五分钟。','熙兰拉面':'门帘被热气顶起来一下，像店里对你点了头。','57store':'自动门响了一声。夜班灯光把每个人照得像临时任务。','几丁质功能饮料自动贩卖机':'机器独自在墙边发光，像一间只有零点五平方米的餐厅。','拾叁面包房':'最后一炉面包还温着，玻璃柜已经开始准备下班。'};
const GYM_EVENT_POOLS=[
 [{who:'长椅',text:'有人把毛巾忘在了你旁边。',choices:[{id:'desk',label:'交给前台',line:'前台贴了一张纸：失物招领，不招领训练计划。',delta:{trust:2}},{id:'wait',label:'先放在显眼处',line:'失主冲回来时，对你做了一个非常郑重的合十。',delta:{social:1}}]}],
 [{who:'泡沫轴',text:'它滚到了队友脚边，像发出挑战。',choices:[{id:'roll',label:'顺便放松一下',line:'最痛的地方被准确找到，像一次不太友好的搜索。',delta:{recovery:3,awareness:1}},{id:'return',label:'把它送回原位',line:'器械归位。秩序感偷偷恢复了一点。',delta:{discipline:1}}]}],
 [{who:'巡场教练',text:'“你这个动作，最后两次开始借力了。”',choices:[{id:'light',label:'减轻一点再做',line:'重量少了，动作反而显得更像自己的。',delta:{awareness:2,recovery:1}},{id:'film',label:'请队友拍一组',line:'镜头没有偏见，只把每一次晃动诚实保存。',delta:{discipline:2,sync:1}}]}],
 [{who:'隔壁训练者',text:'对方刚完成一个漂亮的新纪录，整排器械都听见了。',choices:[{id:'clap',label:'跟着鼓掌',line:'掌声没有减少你的重量，倒让空气轻了一点。',delta:{social:2,confidence:1}},{id:'focus',label:'继续自己的节奏',line:'别人的高光过去以后，你的下一组还在这里。',delta:{discipline:2}}]}],
 [{who:'团课教室',text:'门没关严，音乐和口号一起漏出来。',choices:[{id:'peek',label:'进去体验十分钟',line:'你在第八分钟才发现自己一直站错方向。',delta:{curiosity:2,cardio:1,mood:2}},{id:'pass',label:'还是完成原计划',line:'玻璃门合上，节拍器重新只属于你。',delta:{discipline:2}}]}],
 [{who:'前台抽奖箱',text:'消费满额可以抽一次。奖品从毛巾到“再来一周”。',choices:[{id:'draw',label:'伸手抽一张',line:'是一张饮料券。命运很具体，也很会促销。',delta:{curiosity:2,mood:1},cost:6},{id:'skip',label:'把机会留到下次',line:'箱子没有挽留你，只在出口继续闪。',delta:{thrift:2}}]}],
 [{who:'镜子',text:'最后一天的动作，和第一天看起来已经不太一样。',choices:[{id:'finish',label:'按现在的节奏收尾',line:'没有烟花，但最后一次落地很稳。',delta:{discipline:2,confidence:2}},{id:'teach',label:'把学会的诀窍告诉新人',line:'讲到一半，你发现自己真的已经会讲了。',delta:{social:2,confidence:1}}]}]
];
const AFTER_EVENT_POOLS=[
 [{who:'路口',text:'共享单车座椅上有一小片雨水。',choices:[{id:'wipe',label:'找纸擦掉再骑',line:'裤子保住了。今天的胜利项目临时增加一项。',delta:{mood:1}},{id:'walk',label:'干脆走回去',line:'晚风把腿部的酸胀慢慢摊平。',delta:{recovery:2}}]}],
 [{who:'群聊',text:'朋友问：“第二天还活着吗？”',choices:[{id:'photo',label:'拍一张鞋尖回复',line:'照片没有证明什么，但收获了三个表情包。',delta:{social:2}},{id:'truth',label:'诚实汇报酸痛',line:'对面回：“很好，这说明楼梯明天有剧情。”',delta:{trust:2}}]}],
 [{who:'便利贴',text:'口袋里摸到教练写的动作提示。',choices:[{id:'keep',label:'贴到书桌边',line:'它和待办事项站在一起，显得格外有行动力。',delta:{discipline:2}},{id:'share',label:'发给训练搭子',line:'对方回了句：“原来你也没听懂第一遍。”',delta:{sync:2}}]}],
 [{who:'深夜',text:'身体很累，脑子却还在回放今天那次漂亮完成。',choices:[{id:'sleep',label:'把手机扣下',line:'那次完成留到了梦里，没有继续加班。',delta:{sleep:2,recovery:1}},{id:'search',label:'再搜一会动作教程',line:'你学会了三个新术语，也失去了一小段睡眠。',delta:{curiosity:2,sleep:-2}}]}],
 [{who:'账单通知',text:'今天的消费比平时醒目一点。',choices:[{id:'note',label:'记一下都花在哪',line:'数字没有变小，但终于排成了能看懂的一行。',delta:{discipline:1,thrift:2}},{id:'mute',label:'先划掉通知',line:'通知消失了，支付软件对此保留记忆。',delta:{mood:1}}]}],
 [{who:'电梯',text:'有人按住开门键，等你用很慢的速度走进来。',choices:[{id:'thanks',label:'笑着道谢',line:'你们一起对着不断闪烁的关门键保持克制。',delta:{social:1,mood:1}},{id:'stairs',label:'还是走楼梯活动一下',line:'第三层时你重新评估了“活动一下”的语义。',delta:{recovery:1,confidence:1}}]}],
 [{who:'床边',text:'体验卡明天失效。运动鞋仍旧摆在最顺手的位置。',choices:[{id:'leave',label:'先不收起来',line:'这不算续费，也不算承诺。只是明早不用再找。',delta:{confidence:2}},{id:'clean',label:'把鞋底擦干净',line:'灰尘被擦掉，这一周没有。',delta:{discipline:2}}]}]
];

export const APPEARANCE={
  hair:['短碎发','蓬松卷发','齐肩直发','高马尾','寸头','双丸子'],hairColor:['夜黑','栗棕','雾银','莓红','湖蓝'],eyes:['深棕','灰蓝','琥珀','墨绿'],
  top:['宽松 T 恤','短款卫衣','运动背心','薄夹克','网球衫','暗色乐队T恤','复古球衣','机能短外套','条纹破洞针织'],bottom:['工装长裤','运动短裤','百褶裙','宽松长裙','束脚裤','拼接束带裤','格纹层叠裙'],shoes:['旧跑鞋','高帮帆布鞋','训练鞋','厚底运动鞋','黑色厚底靴'],accessory:['没有配件','圆框眼镜','发带','耳饰','棒球帽','彩色腕带','银色链条','不对称耳夹','像素徽章'],body:['轻巧','修长','结实','圆润']
};
const NAMES=['阿满','乔安','小海','木木','迟夏','冬青'];
const RELATIONS=['常约饭的朋友','同事兼训练搭子','认识很久的网友','住在附近的人','关系有点微妙的人'];
export const CHARACTER_DATA=[
  {id:'xixi',name:'熙熙',relation:'看起来有备而来。',focus:'strength',bias:{strength:2,awareness:2,recovery:1},rates:{train:88,meal:72,cancel:5,extra:30,rest:18},look:{hair:2,hairColor:0,eyes:1,top:2,bottom:4,shoes:2,accessory:1,body:2},events:{train:['熙熙把手机架好：“这一组留给动作分析，不留给朋友圈。”','熙熙算完组数，顺便把休息时间也做成了对照实验。'],meal:['熙熙发来一张菜单截图，圈了一个加蛋选项。'],ending:['这周动作挺稳。下次硬拉我带小饼干，也带一张不太吓人的表格。','报告看了。先睡够，再谈加重量——这是建议，不是审稿意见。'] }},
  {id:'feifei',name:'飞飞',relation:'笑点暂时无法共享。',focus:'cardio',bias:{cardio:1,mood:2,social:1},rates:{train:68,meal:90,cancel:12,extra:8,rest:45},look:{hair:4,hairColor:0,eyes:0,top:0,bottom:1,shoes:0,accessory:4,body:1},events:{train:['飞飞宣布今天以健康为主，然后把组间休息精确成了 11:45.14。','飞飞劝你别拼命：“能走去吃饭，才算完整闭环。”'],meal:['飞飞发来 dx捕鲸堡 的优惠券，声称这是训练后哲学。'],ending:['七天，114514 分……算了，健康就行。下次去 dx捕鲸堡，我请你加一片。','你居然真练完了。结论：身体健康，数字不便解释。'] }},
  {id:'y',name:'Y.',relation:'正在忙。忙什么没说。',focus:'balanced',bias:{discipline:2,adaptability:1,thrift:1},rates:{train:55,meal:60,cancel:32,extra:4,rest:55},look:{hair:0,hairColor:0,eyes:3,top:3,bottom:0,shoes:0,accessory:1,body:1},events:{train:['Y. 在最后一刻赶到，背包里同时装着电脑和一盒自己做的饭。','Y. 的工作消息亮了三次。TA把手机扣下，完成了这一组。'],meal:['Y. 发来消息：今天不自己做饭了，等会碰头。'],ending:['这周像一个没写完的分支，但至少已经能跑。下次我做饭，你负责别临时加练。','忙完才看到。七天都在，挺好。别问我凌晨为什么也在线。'] }},
  {id:'meng',name:'孟总',relation:'名字听着比本人忙。',focus:'mobility',bias:{recovery:1,trust:2,social:1},rates:{train:72,meal:78,cancel:10,extra:6,rest:60},look:{hair:0,hairColor:1,eyes:0,top:4,bottom:4,shoes:2,accessory:0,body:3},events:{train:['孟总没说“加油”，只是默默替你把下一组重量调到了合适的位置。','孟总下班准时出现，训练也准时结束，像一次没有延期的版本。'],meal:['孟总问大家想吃什么，认真读完每一个互相矛盾的答案。'],ending:['体验周辛苦了。你看起来比第一天放松一点。下周有空再约，不用勉强。','我把合照存了。虽然很糊，但大家都没被裁出画面。'] }},
  {id:'deng',name:'邓子',relation:'头像很久没换了。',focus:'balanced',bias:{mood:1,curiosity:1},rates:{train:0,meal:30,cancel:45,extra:0,rest:80},look:{hair:4,hairColor:0,eyes:0,top:0,bottom:0,shoes:1,accessory:0,body:0},events:{train:['门口像是闪过了邓子。再看时，只剩一台刚关上的自动贩卖机。'],meal:['邓子发来一句“附近”。没有说明多近。','邓子说“路过”，问你们吃饭的地方定了没有。'],ending:['嗯。下次吃饭叫我。','看到了。你们练，我负责找店。'] }},
];

CHARACTER_DATA.push(...NEW_CHARACTERS);
for(const p of CHARACTER_DATA)if(['feifei','deng'].includes(p.id))p.preferredStores=['dx捕鲸堡'];
for(const [id,rows] of Object.entries(NEW_FRIEND_ROWS)){FRIEND_EVENTS[id]=rows;FRIEND_PHASES[id]=rows.map((_,i)=>i<7?'train':'meal')}
for(const [store,items] of Object.entries(EXTRA_MENUS))MENUS[store].push(...items);
installVariety({FRIEND_EVENTS,FRIEND_PHASES,GYM_EXTRAS,NIGHT_EXTRAS,FRIEND_GROUPS,CHARACTER_DATA});
for(const [key,lines] of Object.entries(MORE_MIRROR))MIRROR_POOLS[key].push(...lines);
GROUP_REPLIES.push(...MORE_REPLIES);
for(const [store,rows] of Object.entries(MORE_MENU))MENUS[store].push(...rows.map((row,i)=>{const [name,icon,price,line]=row.split('|');return {id:'r6-food-'+i,name,icon,price:Number(price),line,delta:store==='几丁质功能饮料自动贩卖机'?{curiosity:2,mood:1}:{fuel:2,recovery:1}}}));
export const START_QUESTIONS=[
  {who:'57training 前台',text:'“最近一次规律运动，大概是什么时候？”',choices:[{id:'recent',label:'最近还算规律，只是想换个节奏',line:'前台点点头：“那就别把体验周练成毕业考试。”',points:[2,2,2],delta:{discipline:2},tags:['regular']},{id:'months',label:'几个月前，记忆还有一点',line:'“很好，身体可能记得。也可能只记得酸痛。”',points:[2,2,1],delta:{awareness:1},tags:['returning']},{id:'long',label:'上次规律运动像是上一季的事',line:'前台把表格翻到背面：“那我们从能回家开始。”',points:[1,1,2],delta:{recovery:2},tags:['restart']}]},
  {who:'57training 前台',text:'“今天更想练到哪种感觉？”',choices:[{id:'solid',label:'想稳稳地发上力',line:'“收到。重量可以慢慢加，表情不用。”',points:[2,0,0],delta:{confidence:1},tags:['power']},{id:'breath',label:'想让呼吸别先乱',line:'“那先找节奏，不跟跑步机吵架。”',points:[0,2,0],delta:{discipline:1},tags:['pace']},{id:'loose',label:'想让身体别像折叠椅',line:'“合理。先看看哪些关节还愿意开会。”',points:[0,0,2],delta:{awareness:1},tags:['flow']},{id:'unknown',label:'不知道，先进去再说',line:'“也行。体验卡本来就是合法的试试看。”',points:[1,1,1],delta:{curiosity:2},tags:['curious']}]},
  {who:'57training 前台',text:'“昨晚睡得怎么样？工作今天还追你吗？”',choices:[{id:'good',label:'睡够了，消息也暂时安静',line:'前台看了眼空荡荡的通知栏：“稀有状态，请谨慎使用。”',points:[1,1,1],delta:{sleep:2,recovery:1},tags:['rested']},{id:'busy',label:'一般，脑子还挂着几个窗口',line:'“先别关机。今天给身体留一点内存。”',points:[0,1,1],delta:{sleep:-1,adaptability:2},tags:['busy']},{id:'bad',label:'不太行，但人已经到这里了',line:'“到场算一件事，硬撑是另一件事。”',points:[0,0,1],delta:{sleep:-2,recovery:2,awareness:1},tags:['tired']}]},
  {who:'你',text:'换鞋的时候，我又问了自己一遍：到底为什么会来？',choices:[{id:'prove',label:'想看看自己到底能不能坚持',line:'这个答案有一点用力，但鞋带已经系好了。',points:[1,1,0],delta:{discipline:2,confidence:1},tags:['prove']},{id:'company',label:'有人一起，来都来了',line:'听起来不宏大。刚好足够推开那扇门。',points:[0,1,1],delta:{social:2,trust:1},tags:['company']},{id:'change',label:'最近想让生活有一点变化',line:'变化暂时只有一张体验卡和一双旧鞋。也算开始。',points:[1,0,1],delta:{curiosity:2,adaptability:1},tags:['change']},{id:'food',label:'练完以后，吃饭会更理直气壮',line:'理由非常具体。胃对此表示支持。',points:[1,1,0],delta:{mood:2,impulse:1},tags:['food']}]}
];

export function hash(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function randomSeed(){return (Date.now()^Math.floor(Math.random()*0xffffffff))>>>0}
export function defaultLook(seed=1,index=0){const look={};for(const [key,values] of Object.entries(APPEARANCE))look[key]=hash(`${seed}:${index}:${key}`)%values.length;return look}
function baseStats(focus,points){if(points&&points.length===3&&points.every(Number.isFinite))return {strength:points[0],cardio:points[1],mobility:points[2]};return {strength:focus==='strength'?4:focus==='balanced'?2:1,cardio:focus==='cardio'?4:focus==='balanced'?2:1,mobility:focus==='mobility'?4:focus==='balanced'?2:1}}
export function createCharacter(seed,index,spec={}){const focus=spec.focus||['balanced','strength','cardio','mobility'][hash(`${seed}:focus:${index}`)%4],base=baseStats(focus,spec.points),bias=spec.bias||{};return {id:spec.id||`p${index}`,name:String(spec.name||NAMES[hash(`${seed}:name:${index}`)%NAMES.length]).slice(0,10),relation:spec.relation||RELATIONS[hash(`${seed}:relation:${index}`)%RELATIONS.length],height:Number(spec.height)||153,weight:Number(spec.weight)||43,look:{...defaultLook(seed,index),...(spec.look||{})},profile:spec.id?spec:null,hidden:{...base,strength:base.strength+(bias.strength||0),cardio:base.cardio+(bias.cardio||0),mobility:base.mobility+(bias.mobility||0),fatigue:0,recovery:5+(bias.recovery||0),sync:0,confidence:2+(bias.confidence||0),proficiency:{},meals:{},sessions:[],body:{legs:0,back:0,shoulders:0}},appearanceMark:null}}
export function presetContacts(seed){return CHARACTER_DATA.map((p,i)=>createCharacter(seed,i+1,p)).sort((a,b)=>hash(`${seed}:contact:${a.id}`)-hash(`${seed}:contact:${b.id}`))}
export function randomFriend(seed,index=1){return createCharacter(seed,index,{name:NAMES[hash(`${seed}:random:${index}`)%NAMES.length],relation:RELATIONS[hash(`${seed}:rel:${index}`)%RELATIONS.length]})}
export function createGame(seed,specs,initial={}){const party=specs.slice(0,4).map((spec,i)=>createCharacter(seed,i,spec));if(!party.length)throw new Error('A player is required');const traits={discipline:0,awareness:0,social:0,curiosity:0,risk:0,adaptability:0,thrift:0,impulse:0,trust:0,confidence:0,...(initial.traits||{})};for(const p of party.slice(1))for(const [key,value] of Object.entries(p.profile?.bias||{}))if(key in traits)traits[key]+=value;const needs={fuel:5,sleep:6,mood:5};for(const [key,value] of Object.entries(initial.needs||{}))needs[key]=(needs[key]||0)+value;for(const p of party.slice(1))for(const [key,value] of Object.entries(p.profile?.bias||{})){if(key in needs)needs[key]+=value;else if(['strength','cardio','mobility','recovery'].includes(key))party[0].hidden[key]+=Math.min(1,value)}return {version:VERSION,seed,groupName:party.length>1?'先试试':'一个人的打卡',groupReplies:[],phoneUnlocked:false,batteryStart:Math.max(45,Math.min(98,52+needs.sleep*4+traits.discipline*2)),day:1,step:'warmup',round:0,party,history:[],interactions:[],last:null,traits,needs,tags:[...(initial.tags||[])],spend:[],stores:{},bonus:false,selectedStore:null,reportViewed:[]}}
export function eventFor(seed,day){const pool=[...EVENT_POOLS[day-1],...GYM_EXTRAS.filter(e=>e.minDay===day)];return pool[hash(`${seed}:event:${day}`)%pool.length]}
export function gymEventFor(seed,day,state){return contextualEvent(seed,day,state,'train',[...GYM_EVENT_POOLS[day-1],...GYM_EXTRAS.filter(e=>e.minDay===day)])}
export function afterEventFor(seed,day,state){return contextualEvent(seed,day,state,'meal',[...AFTER_EVENT_POOLS[day-1],...NIGHT_EXTRAS.filter(e=>e.minDay===day||e.minDay===Math.max(1,day-1))])}
export function attendance(state,phase='train'){return state.party.filter((p,i)=>i===0||(p.id!=='deng'||phase==='meal')&&hash(`${state.seed}:${state.day}:${phase}:${p.id}`)%100<Math.max(0,(p.profile?.rates?.[phase]??65)+(phase==='meal'&&p.profile?.preferredStores?.includes(state.selectedStore)?18:0)-(phase==='train'?(p.profile?.rates?.cancel||0):0)))}
function contextualEvent(seed,day,state,phase,pool){const people=state?attendance(state,phase).slice(1).filter(p=>FRIEND_EVENTS[p.id]):[];const used=new Set((state?.interactions||[]).map(e=>e.eventId));const group=state?groupEventFor(state,phase):null;if(group)return group;if(people.length&&hash(`${seed}:special:${day}:${phase}`)%100<80){if(people.length===2&&!used.has('pair-'+phase)&&hash(`${seed}:pair:${day}:${phase}`)%4===0){const [a,b]=people;return {id:'pair-'+phase,friendIds:people.map(p=>p.id),who:a.name+' / '+b.name,text:phase==='meal'?`${a.name}负责看菜单，${b.name}负责否决。两个人终于一起看向你。`:`${a.name}指向器械，${b.name}指向饮水机。今天的分歧只有三米远。`,choices:[{id:'pair-share',label:phase==='meal'?'选一道一起分':'先一起喝水',line:'意见没有完全统一，事情倒是往前走了一步。',delta:{trust:2,recovery:1}},{id:'pair-own',label:'各按自己的节奏',line:'群聊没有解散，只是暂时分头行动。',delta:{awareness:2}}]}}const ordered=people.slice().sort((a,b)=>hash(`${seed}:pick:${day}:${a.id}`)-hash(`${seed}:pick:${day}:${b.id}`));for(const p of ordered){const indexes=FRIEND_PHASES[p.id].flatMap((v,i)=>v===phase&&!used.has('friend-'+p.id+'-'+i)?[i]:[]);if(indexes.length)return makeFriendEvent(p.id,indexes[hash(`${seed}:detail:${day}:${p.id}`)%indexes.length],p.name)}}const fresh=pool.filter(e=>!used.has(e.id));const available=fresh.length?fresh:pool;return available[hash(`${seed}:${phase}:${day}`)%available.length]}
export function groupEventFor(state,phase){const present=new Set(attendance(state,phase).map(p=>p.id)),used=new Set(state.interactions.map(e=>e.eventId));const eligible=FRIEND_GROUPS.filter(g=>g.members.every(id=>present.has(id)));for(const g of eligible){const candidates=g[phase].map((text,i)=>({text,id:'group-'+g.id+'-'+phase+'-'+i})).filter(e=>!used.has(e.id));if(candidates.length&&hash(`${state.seed}:group:${state.day}:${phase}`)%100<55){const e=candidates[hash(`${state.seed}:${state.day}`)%candidates.length];return {...e,friendIds:g.members,who:g.members.map(id=>state.party.find(p=>p.id===id).name).join(' / '),choices:[{id:e.id+'-join',label:phase==='train'?'加入讨论，顺便动起来':'接过菜单，先点一道',line:'几套不同的思路，终于在同一件小事上碰了头。',delta:{social:2,trust:1}},{id:e.id+'-watch',label:'笑一下，留给TA们继续',line:'你没有插话，倒是完整看完了一场很小的团体生活。',delta:{mood:1,awareness:1}},{id:e.id+'-separate',label:phase==='train'?'约好结束时间，各练各的':'各点各的，坐在一起',line:'共同的时间不必配上相同的计划。大家把位置留着。',delta:{discipline:1,trust:1}}]}}}return null}
export function workoutsFor(seed,day,round=0){return SCHEDULE[day-1].slice().sort((a,b)=>hash(`${seed}:${day}:${round}:${a}`)-hash(`${seed}:${day}:${round}:${b}`)).slice(0,5)}
export function menuFor(seed,day,store){const all=MENUS[store],ordered=all.slice().sort((a,b)=>hash(`${seed}:menu:${store}:${a.id}`)-hash(`${seed}:menu:${store}:${b.id}`)),offset=(day-1+hash(`${seed}:menu-offset:${store}`))%all.length;return Array.from({length:4},(_,i)=>({...ordered[(offset+i)%all.length],soldOut:i===3&&hash(`${seed}:${day}:sold:${store}`)%4===0}))}
const DX_SIDES=[{id:'dx-fries',name:'小份薯条',price:8,line:'薯条到场，纸盘很快失去了留白。',delta:{fuel:1,mood:1}},{id:'dx-corn',name:'热玉米杯',price:7,line:'最后一粒玉米坚持留在杯底。',delta:{fuel:1}},{id:'dx-salad',name:'卷心菜小杯',price:6,line:'脆脆的一口，把酱汁的存在感调低了一点。',delta:{recovery:1}},{id:'dx-soup',name:'奶油蘑菇小汤',price:9,line:'汤比取餐广播温柔一些。',delta:{recovery:1}}];
export function sideFor(state){const sides=state.selectedStore==='dx捕鲸堡'?DX_SIDES:SIDE_DISHES;return state.selectedStore!=='几丁质功能饮料自动贩卖机'&&hash(`${state.seed}:side:${state.day}`)%100<38?sides[hash(`${state.seed}:side-type:${state.day}`)%sides.length]:null}
export function chooseSide(state,id){if(state.step!=='sideOffer')return state;const side=sideFor(state);if(!side||!['yes','no'].includes(id))return state;return {...state,...(id==='yes'?applyTraits(state,side.delta):{}),sideDone:true,step:'sideResult',party:id==='yes'?applyPresent(state,side.delta,'meal'):state.party,spend:id==='yes'?[...state.spend,{day:state.day,store:state.selectedStore,name:side.name,price:side.price,kind:'side'}]:state.spend,last:{kind:'side',id,line:id==='yes'?side.line:'这一顿已经够了。你把多出来的胃口留给明天。'}}}
function recordInteraction(state,event,choice,phase){return [...(state.interactions||[]),...(event.friendIds||[event.friendId||null]).map(friendId=>({day:state.day,friendId,eventId:event.id,choiceId:choice.id,phase}))]}
function applyPresent(state,delta,phase='train'){const ids=new Set(attendance(state,phase).map(p=>p.id));return state.party.map(p=>ids.has(p.id)?applyDelta([p],delta)[0]:p)}
function applyTraits(state,delta={}){const traits={...state.traits};for(const key of Object.keys(traits))traits[key]+=delta[key]||0;const needs={...state.needs};for(const key of Object.keys(needs))needs[key]=Math.max(0,needs[key]+(delta[key]||0));return {traits,needs}}
function applyDelta(party,delta){return party.map(p=>{const h={...p.hidden};for(const [key,value] of Object.entries(delta||{}))h[key]=(h[key]||0)+value;h.fatigue=Math.max(0,h.fatigue-(delta?.recovery||0));return {...p,hidden:h}})}
export function chooseWarmup(state,id){if(state.step!=='warmup')return state;const choice=WARMUPS[state.day-1]?.find(x=>x.id===id);if(!choice)return state;return {...state,step:'warmupResult',party:applyPresent(state,choice.delta),last:{kind:'warmup',line:choice.line,id}}}
export function continueToEvent(state){return state.step==='warmupResult'?{...state,step:'event'}:state}
export function chooseEvent(state,id){if(state.step!=='event')return state;const choice=eventFor(state.seed,state.day).choices.find(x=>x.id===id);if(!choice)return state;return {...state,...applyTraits(state,choice.delta),step:'eventResult',interactions:recordInteraction(state,eventFor(state.seed,state.day),choice,'train'),party:applyPresent(state,choice.delta),last:{kind:'event',line:choice.line,id}}}
export function continueToWorkout(state){return ['eventResult','gymEventResult'].includes(state.step)?{...state,step:'workout'}:state}
export function doWorkout(state,id){if(state.step!=='workout'||!SCHEDULE[state.day-1]?.includes(id))return state;const workout=WORKOUTS[id],target=['split','run','bike'].includes(id)?'legs':['rdl','carry','row'].includes(id)?'back':'shoulders',round=state.round+1;const party=state.party.map((p,index)=>{if(!attendance(state).some(a=>a.id===p.id))return p;const h={...p.hidden,proficiency:{...p.hidden.proficiency},sessions:[...p.hidden.sessions,id],body:{...p.hidden.body}},aptitude=h[workout.main],sore=h.body[target]||0,load=Math.max(1,workout.load+(round===3?1:0));h[workout.main]+=1;h.fatigue+=Math.max(1,load-Math.floor((aptitude+h.recovery)/5)+(state.needs.sleep<5?1:0)+(sore>3?1:0));h.recovery=Math.max(0,h.recovery-1);h.sync+=attendance(state).length>1?1:0;h.confidence+=round===3?2:1;h.proficiency[id]=(h.proficiency[id]||0)+1+(index===0?1:0);h.body[target]=Math.min(6,sore+load);return {...p,hidden:h}});const h=party[0].hidden,line=round===3?'额外一回合结束。兴奋还在，腿已经开始填写不同意见。':h.fatigue>=7?'最后两次，你把动作换成了更稳妥的版本。今天的完成感没有因此打折。':round===1?'第一段正式训练结束。呼吸慢慢回到能说完整句子的速度。':'第二段完成时，刚才还陌生的动作已经顺手了一点。';return {...state,step:'workoutResult',round,party,needs:{...state.needs,fuel:Math.max(0,state.needs.fuel-1)},last:{kind:'workout',id,line}}}
export function continueAfterWorkout(state){if(state.step!=='workoutResult')return state;if(state.round===1)return {...state,step:'gymEvent'};if(state.round===2){const bonus=state.day>=3&&hash(`${state.seed}:burst:${state.day}`)%100<Math.max(5,[0,0,38,45,35,20,48][state.day-1]+attendance(state).slice(1).reduce((sum,p)=>sum+(p.profile?.rates?.extra||0)/3-(p.profile?.rates?.rest||0)/5,0));return {...state,bonus,step:bonus?'bonusOffer':'mealPlace'}}return {...state,step:'mealPlace'}}
export function chooseGymEvent(state,id){if(state.step!=='gymEvent')return state;const choice=gymEventFor(state.seed,state.day,state).choices.find(x=>x.id===id);if(!choice)return state;const spend=choice.cost?[...state.spend,{day:state.day,store:'57training',name:'馆内小消费',price:choice.cost,kind:'gym'}]:state.spend;return {...state,...applyTraits(state,choice.delta),spend,interactions:recordInteraction(state,gymEventFor(state.seed,state.day,state),choice,'train'),step:'gymEventResult',party:applyPresent(state,choice.delta),last:{kind:'gymEvent',line:choice.line,id}}}
export function chooseBonus(state,id){if(state.step!=='bonusOffer')return state;if(id==='go')return {...state,step:'bonusResult',last:{kind:'bonus',id,line:'状态像突然多开了一扇门。你决定进去再练一回合。'}};return {...state,step:'bonusResult',traits:{...state.traits,awareness:state.traits.awareness+1},last:{kind:'bonus',id,line:'你把这点余裕留给恢复。能继续，不等于必须继续。'}}}
export function continueAfterBonus(state){if(state.step!=='bonusResult')return state;return {...state,step:state.last.id==='go'?'workout':'mealPlace'}}
export function chooseStore(state,store){if(state.step!=='mealPlace'||!storesFor(state.seed,state.day,state).includes(store))return state;const next={...state,step:'mealPlaceResult',selectedStore:store};const fans=store==='dx捕鲸堡'?attendance(next,'meal').filter(p=>p.profile?.preferredStores?.includes(store)):[];return {...next,last:{kind:'store',store,line:STORE_ARRIVALS[store]+fans.map(p=>p.id==='feifei'?' 飞飞回得很快：“这个地址不用导航。”':' 邓子发来“这家可以”，随后补了一句：“给我留个位。”').join('')}}}
export function continueToMenu(state){return state.step==='mealPlaceResult'?{...state,step:'meal'}:state}
export function chooseMeal(state,id){if(state.step!=='meal')return state;const [store,key]=id.split('|'),meal=MENUS[store]&&menuFor(state.seed,state.day,store).find(item=>item.id===key&&!item.soldOut);if(!meal||store!==state.selectedStore)return state;const party=state.party.map(p=>{if(!attendance(state,'meal').some(a=>a.id===p.id))return p;const h={...p.hidden,meals:{...p.hidden.meals}};h.meals[store]=(h.meals[store]||0)+1;h.fatigue=Math.max(0,h.fatigue-(meal.delta.recovery||0));h.recovery+=(meal.delta.recovery||0);return {...p,hidden:h}});return {...state,...applyTraits(state,meal.delta),step:'mealResult',mainMeal:{id,store},party,spend:[...state.spend,{day:state.day,store,name:meal.name,price:meal.price,kind:'meal'}],stores:{...state.stores,[store]:(state.stores[store]||0)+1},last:{kind:'meal',id,store,line:meal.line}}}
export function continueAfterMeal(state){if(!['mealResult','sideResult'].includes(state.step))return state;if(!state.sideDone&&sideFor(state))return {...state,step:'sideOffer'};return {...state,step:'afterEvent',history:[...state.history,{day:state.day,workouts:state.party[0].hidden.sessions.slice(-state.round),meal:state.mainMeal?.id||state.last.id,bonus:state.bonus,trainingFriends:attendance(state).slice(1).map(p=>p.id),mealFriends:attendance(state,'meal').slice(1).map(p=>p.id)}]}}
export function chooseAfterEvent(state,id){if(state.step!=='afterEvent')return state;const choice=afterEventFor(state.seed,state.day,state).choices.find(x=>x.id===id);if(!choice)return state;return {...state,...applyTraits(state,choice.delta),step:'afterEventResult',interactions:recordInteraction(state,afterEventFor(state.seed,state.day,state),choice,'meal'),party:applyPresent(state,choice.delta,'meal'),last:{kind:'afterEvent',line:choice.line,id}}}
export function continueAfterEvent(state){return state.step==='afterEventResult'?{...state,step:'summary'}:state}
export function advanceDay(state){if(state.step!=='summary')return state;if(state.day===7){const party=state.party.map(p=>({...p,appearanceMark:appearanceRoute(p)}));return {...state,step:'epilogue',party,last:null}}const party=state.party.map(p=>({...p,hidden:{...p.hidden,recovery:Math.min(12,p.hidden.recovery+(state.needs.sleep>=6?2:1)),fatigue:Math.max(0,p.hidden.fatigue-(state.needs.sleep>=6?2:1)),body:Object.fromEntries(Object.entries(p.hidden.body).map(([k,v])=>[k,Math.max(0,v-2)]))}}));return {...state,party,day:state.day+1,step:'warmup',round:0,bonus:false,sideDone:false,mainMeal:null,last:null,needs:{...state.needs,fuel:5,sleep:Math.max(3,Math.min(8,state.needs.sleep))}}}
export function compositeMetrics(state){const h=state.party[0].hidden;return {drive:Math.max(1,Math.min(5,Math.round((h.strength+h.cardio+h.mobility+h.confidence)/5))),rhythm:Math.max(1,Math.min(5,Math.round((h.recovery+state.needs.sleep+state.traits.discipline-state.traits.impulse)/5))),fatigue:Math.max(1,Math.min(5,Math.round((h.fatigue+Math.max(...Object.values(h.body))+(8-state.needs.sleep))/4))),connection:Math.max(1,Math.min(5,Math.round((h.sync+state.traits.social+state.traits.trust+2)/5)))}}
export function appearanceRoute(character){const h=character.hidden,counts={};for(const id of h.sessions)counts[WORKOUTS[id].main]=(counts[WORKOUTS[id].main]||0)+1;const meals=Object.values(h.meals).reduce((a,b)=>a+b,0),entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);if(meals>=6&&new Set(Object.keys(h.meals)).size>=3)return'store';if((counts.strength||0)>=Math.max(counts.cardio||0,counts.mobility||0))return'power';if((counts.mobility||0)>=(counts.cardio||0))return'flow';return'runner'}
export function endingText(route,name){return ({power:`${name}换衣服时，发现袖口比一周前紧了。再抬手，T 恤干脆变成了很有主张的背心。`,flow:`${name}站着系鞋带，身体顺手折成了一个过分流畅的角度。宽松下装似乎终于理解了这份工作。`,runner:`${name}下楼买水，走到街口才发现自己一直在控制呼吸。发带和轻装已经自动进入值班状态。`,store:`57store 店员把袋子递给${name}：“还是老样子？”这一周别的不说，熟客造型已经完全成立。`})[route]}

export function companionMoment(state,phase){const present=new Set(attendance(state,phase).map(p=>p.id));return state.party.slice(1).map(p=>{if(phase==='meal'&&!present.has(p.id))return '';if(p.id==='deng'&&phase==='train')return p.name+ARRIVALS.deng[state.day-1];if(!present.has(p.id))return p.name+'：'+ABSENT_REASONS[(state.day-1+hash(p.id)%7)%7];return p.name+(phase==='train'?(ARRIVALS[p.id]?.[state.day-1]||'到了，先跟你打招呼。'):(MEAL_ARRIVALS[p.id]?.[state.day-1]||'问今晚去哪边。'))}).filter(Boolean).join(' ')}
export function paymentProfile(state){const t=state.traits,meals=state.spend.filter(x=>x.kind==='meal'),stores=Object.keys(state.stores).length,counts=Object.values(state.stores),total=state.spend.reduce((n,x)=>n+x.price,0),sides=state.spend.filter(x=>x.kind==='side').length;const profiles=[
['小菜外交官',sides>=3?80+sides:0,'主菜解决饥饿，小菜负责让桌面变热闹。你给余地也留了一笔预算。'],
['异种风味观察员',(state.stores['几丁质功能饮料自动贩卖机']||0)>=2?75+t.curiosity:0,'几次取货口前的停留，让账单短暂具备了自然纪录片的气质。'],
['城市菜单测绘员',stores>=6?85:0,'熟悉的不是某一道菜，而是这几条通向晚饭的路。'],
['老位置守望者',Math.max(0,...counts)>=4?82:0,'同一家店重复出现。账单叫它集中消费，你可能叫它省心。'],
['便利生活实践者',(state.stores['57store']||0)>=3?81:0,'你把晚饭安排在顺路的地方，让生活少拐几个弯。'],
['面包时间收藏家',(state.stores['拾叁面包房']||0)>=3?81:0,'纸袋里的香味，多次替一天划出了温柔的边界。'],
['清醒预算派',t.thrift>t.impulse+2?70+t.thrift:0,'你给欲望留位置，也给明天留下余额。'],
['奖励驱动派',t.impulse>t.thrift+2?70+t.impulse:0,'你会把晚饭当作完成一天的回执，偶尔还附赠小菜。'],
['轻装结算者',total>0&&total<=150?65:0,'这周的收据不厚，日子并不因此稀薄。'],
['热汤缓冲带',meals.filter(x=>/汤|面|粥|乌冬/.test(x.name)).length>=4?83:0,'你多次用一点热气，把训练和回家接在一起。'],
['关系型续航者',t.social+t.trust,'饭桌不仅提供食物，也提供不用立刻离开的理由。'],
['即兴探索派',t.curiosity+t.risk,'你愿意在熟悉的一周里，给没点过的东西留一票。'],
['稳定调整派',t.discipline+t.awareness,'决定可以重复，也可以小幅修改。你没有把晚饭变成另一场考试。'],
['随身小休止',t.adaptability+3,'你把七天切成可以处理的小段，吃饭是其中很明确的一段。']];
const ranked=profiles.map(([name,score,line])=>({name,score,line})).sort((a,b)=>b.score-a.score);return ranked[0]}
export function friendEndingMessages(state){return state.party.slice(1).map(p=>{const pool=p.profile?.events?.ending||['下次还可以再约。'],count=state.interactions.filter(e=>e.friendId===p.id).length,meals=state.history.filter(d=>d.mealFriends?.includes(p.id)).length,training=state.history.filter(d=>d.trainingFriends?.includes(p.id)).length,index=hash(`${state.seed}:ending:${p.id}:${count}`)%pool.length;const facts=p.id==='deng'?(meals?'这周饭点碰见过。下次也发地址。':'这周饭点没碰上。下次发地址。'):({xixi:`记录补上：同行训练 ${training} 天，一起吃饭 ${meals} 天。`,feifei:`健康任务碰头 ${training} 天，饭点碰头 ${meals} 天，后者很好记。`,y:`日程里空出了 ${training} 天碰头训练，还有 ${meals} 天吃饭。`,meng:`在馆里见了 ${training} 天，饭桌边见了 ${meals} 天，都挺好的。`,dai:`实践样本：一起练 ${training} 天，一起吃 ${meals} 天。有感觉吗？`,kevin:`核对过了，训练碰头 ${training} 天，吃饭 ${meals} 天。`,mystery:`这一周的画面里，训练同框 ${training} 天，饭桌同框 ${meals} 天。`}[p.id]||`一起练了 ${training} 天，吃了 ${meals} 天饭。`);return {id:p.id,name:p.name,line:[pool[index],facts,pool.length>1?pool[(index+1+hash(p.id)%(pool.length-1))%pool.length]:''].join(' ')}})}

const EPILOGUE_LINES=['居然真的坚持了一周。','第七天结束的时候，身体还没有申请离职。','体验卡的边角已经起毛，计划倒还算完整。','最后一次关上储物柜，声音和第一天差不多。人不太一样。','七天没有让生活焕然一新，只让楼梯稍微讲了点道理。','手表安静了几秒，像也在确认这件事真的发生过。','镜子没有播放胜利动画。幸好手机替它震了一下。','运动鞋还在脚上，没有变成奖杯。这很合理。','你站在门口，突然想不起第一天为什么那么紧张。','身体逐项清点完酸痛，勉强批准了本周结案。'];
export function epilogueLines(state){const start=hash(`${state.seed}:epilogue`)%EPILOGUE_LINES.length;return [EPILOGUE_LINES[start],EPILOGUE_LINES[(start+3)%EPILOGUE_LINES.length],EPILOGUE_LINES[(start+7)%EPILOGUE_LINES.length]]}

const THOUGHT_POOLS={
  steady:['原来规律不一定要很响，它也可以只是鞋一直放在门边。','有几次我只是照计划做完，居然也很满足。','下周如果继续，我想把“刚好”练得更熟一点。','身体没有突然变成别人，只是更愿意配合我了。','我开始能分清不想练，和真的该休息。','七天不算答案，但至少已经不是空白。','我记住的不是最重那次，是动作最稳那次。','也许坚持并不是每天都要证明自己。'],
  curious:['我好像不是来执行计划的，是来不断修改计划的。','没想到一家店、一首歌，也能改变今天练成什么样。','下次还想试试没选过的动作，但先把今晚睡完。','新鲜感确实有用，只是它不负责替我恢复。','这一周像把身体当成一座刚开放参观的小城。','我仍然不知道最适合什么，不过已经知道几样不适合。','那些临时决定，最后居然拼成了一条路线。','如果再来一次，我大概还是会点那个无标签饮料。'],
  social:['原来我记得最清楚的，是有人替我数最后两次。','一起练没有让重量变轻，但让休息时间变得很好笑。','下周要不要再约？这次先把餐厅决定好。','有人在旁边时，我似乎更愿意承认今天做不到。','合照很糊，不过大家确实都在里面。','我以为自己来练身体，结果顺便更新了几段关系。','被等一下、提醒一下、笑一下，也算训练的一部分。','如果一个人来，可能会快一点；但不会是这一周。'],
  tired:['我不是失败，只是身体比计划先抵达周末。','现在最诚实的训练项目，应该是睡觉。','几次硬撑当时很帅，第二天的楼梯对此有不同评价。','下周要把恢复写进日程，不再放在愿望里。','身体已经把账单寄来了，而且拒绝分期。','原来停下来也需要练习，我这周练得还不够。','最后一天没有奇迹，只有终于愿意听清楚的疲惫。','如果明天醒来还能正常坐下，我会认真感谢自己。'],
  food:['我记住了几个动作，也记住了哪家店会问“还是老样子”。','训练结束之后的那顿饭，好像才是每天真正的句号。','支付记录很诚实：我的恢复计划有一半写在菜单上。','下周继续之前，也许应该先做一张饭店轮值表。','身体的变化很慢，店员认出我的速度倒很快。','我很难说最喜欢哪次训练，但最喜欢哪顿饭很清楚。','原来“吃什么”也是一种每天都会暴露性格的选择。','七天以后，路线没记全，菜单倒已经背得差不多。']
};

SCHEDULE.forEach((pool,i)=>pool.push(...EXTRA_SCHEDULE[i]));
const hasDOM=typeof document!=='undefined';
if(hasDOM){
  const $=id=>document.getElementById(id);let seed=randomSeed(),screen='intro',gameState=null,animating=false,frame=0,raf=0,pendingAction='',dialogueRun=0,drawTimer=0,invitesSent=false,inviteDecision=false,rewound=false;const trainingStart=new Date();trainingStart.setHours(12,0,0,0);
  let card={name:'',height:'153',weight:'43',points:[1,1,1],look:defaultLook(seed,0),question:0,answers:[],traits:{},needs:{},tags:[]};
  let contacts=presetContacts(seed),selected=[],custom=null;const scrollPositions={look:0,phone:0};
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button=(act,label,attrs='')=>`<button type="button" class="choice" data-act="${esc(act)}" ${attrs}>${label}</button>`;
  const isPhone=()=>!gameState?screen==='phone':['lockscreen','inbox','reportGym','reportPay','reportFriend'].includes(gameState.step);
  function phoneStatus(){const now=new Date(),time=now.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),battery=gameState?Math.max(12,gameState.batteryStart-(gameState.day-1)*6):Math.max(45,Math.min(98,76+(card.needs.sleep||0)*4+(card.traits.discipline||0)*2));return `<div class="phone-status"><span><time class="phone-now">${time}</time> · 57Signal</span><span>▂▄▆ ▰ ${battery}%</span></div>`}
  const stage=(label,place,body)=>gameState&&['reportSelf','weekEnding'].includes(gameState.step)?`<section class="mirror-screen">${body}</section>`:isPhone()?`<section class="pixel-handset ${gameState?.step==='lockscreen'?'is-locked':''}">${phoneStatus()}${gameState?.step==='lockscreen'?'':`<header class="chat-nav">${gameState&&gameState.step!=='inbox'?button('inbox','‹'):!gameState?button(invitesSent?'editInvites':'inviteGate','‹'):'<span>‹</span>'}<strong>${gameState?.step==='reportFriend'?esc(gameState.groupName):gameState?.step==='reportGym'?'57training':gameState?.step==='reportPay'?'57pay':gameState?'聊天':invitesSent?'先试试':'选择群成员'}</strong><span>···</span></header>`}${gameState?.step==='lockscreen'?'':'<div class="phone-music">♫ 最近播放 · SIDE B / 夜路</div>'}<div class="chat-screen">${body}</div><footer class="phone-bottom"><span>${gameState?'消息仅保留在本次体验中':'通讯录 · 本机好友'}</span><button data-act="restart">重新开始</button></footer><div class="phone-home" aria-hidden="true">━━━━</div></section>`:`<section class="screen"><div class="stage-shell"><canvas class="stage scene-${esc(sceneName())}" id="stage" width="240" height="160" aria-label="${esc(place)}的复古像素场景"></canvas><span class="stage-label">${esc(label)}</span><span class="stage-place">${esc(place)}</span>${watchHud()}<i class="scanlines"></i></div>${body}</section>`;
  const box=(speaker,content,classes='')=>`<div class="box${classes?' '+classes:''}">${speaker&&!['旁白','镜子'].includes(speaker)?`<div class="speaker">${esc(speaker)}</div>`:''}${content}</div>`;
  const option=(act,label,disabled=false)=>`<button type="button" class="choice select-option" data-act="selectChoice" data-choice="${esc(act)}" aria-pressed="false" ${disabled?'disabled':''}>${label}</button>`;
  const selection=(items,classes='',footer='')=>`<div class="dialogue-actions" hidden><div class="choices${classes?' '+classes:''}">${items.map(item=>option(item.act,item.label,item.disabled)).join('')}</div>${footer}<button type="button" class="choice confirm-choice" data-act="confirmChoice" disabled>确定</button></div>`;
  const delayedAction=content=>`<div class="dialogue-actions next" hidden>${content}</div>`;
  function announce(text){$('announcement').textContent=text}
  function currentParty(){return (gameState?attendance(gameState,/meal|side|afterEvent/.test(gameState.step)?'meal':'train'):null)||[createCharacter(seed,0,{name:card.name||'你',height:card.height,weight:card.weight,points:card.points,look:card.look}),...selected.map(id=>contacts.find(x=>x.id===id)).filter(Boolean),...(custom?[custom]:[])].slice(0,4)}
  function sceneName(){if(screen==='card')return'card';if(screen==='questions')return card.question<3?'desk':'locker';if(screen==='look')return'locker';if(screen==='phone')return'phone';if(!gameState)return'bedroom';if(gameState.step==='mealPlace'||gameState.step==='mealPlaceResult')return'outside';if(['meal','mealResult','sideOffer','sideResult'].includes(gameState.step))return`store-${storeScene(gameState.selectedStore||gameState.last?.store)}`;if(['epilogue'].includes(gameState.step))return'outside-night';if(['inbox','reportGym','reportPay','reportFriend','reportSelf'].includes(gameState.step))return'phone';if(['afterEvent','afterEventResult','summary','weekEnding'].includes(gameState.step))return'room';if(gameState.step==='workoutResult')return'watch';if(['warmup','warmupResult'].includes(gameState.step))return'warmup';if(['gymEvent','gymEventResult'].includes(gameState.step))return'gym-side';return'gym'}
  function storeScene(store){if(store==='dx捕鲸堡')return'fastfood';if(store==='57store')return'convenience';if(store==='几丁质功能饮料自动贩卖机')return'vending';if(store==='拾叁面包房')return'bakery';return'diner'}
  function gameDate(day=1){const date=new Date(trainingStart);date.setDate(trainingStart.getDate()+day-1);return `${date.getMonth()+1}/${date.getDate()}`}
  function watchTime(){return ({warmup:'07:38',warmupResult:'07:46',event:'07:49',eventResult:'07:55',workout:'08:03',workoutResult:'08:29',gymEvent:'08:32',gymEventResult:'08:36',bonusOffer:'09:01',bonusResult:'09:03',mealPlace:'09:14',mealPlaceResult:'09:17',meal:'09:20',mealResult:'09:42',afterEvent:'21:18',afterEventResult:'21:22',summary:'22:16',epilogue:'23:46',inbox:'23:48',reportGym:'23:49',reportPay:'23:52',reportFriend:'23:56',reportSelf:'00:03',weekEnding:'00:08'})[gameState?.step]||'07:24'}
  function metricWord(value,reverse=false){const words=reverse?['轻松','尚可','有感','偏高','告急']:['起步','渐稳','在线','充足','高涨'];return words[Math.max(0,Math.min(4,value-1))]}
  function watchHud(){if(!gameState)return'';const m=compositeMetrics(gameState),metrics=[['STS',m.drive],['PACE',m.rhythm],['LOAD',m.fatigue],['LINK',m.connection]],date=gameDate(gameState.day),time=watchTime();return `<aside class="sport-watch${gameState.step==='workoutResult'?' is-updating':''}" aria-label="运动手表：${date}，${time}；复合指标仅在问号中解释"><span class="watch-strap watch-strap-top" aria-hidden="true"></span><span class="watch-strap watch-strap-bottom" aria-hidden="true"></span><div class="watch-top"><strong class="watch-time">${time}</strong><span class="watch-date">${date}</span><span class="watch-status"><span class="watch-signal" aria-hidden="true"><i></i><i></i><i></i></span><button type="button" class="watch-help" data-act="watchHelp" aria-expanded="false" aria-controls="watchLegend" aria-label="解释手表指标">?</button></span></div><div class="watch-metrics">${metrics.map(([label,value])=>`<span class="watch-metric"><span>${label}</span><strong>${String(value).padStart(2,'0')}</strong></span>`).join('')}</div><div class="watch-legend" id="watchLegend" hidden><span><b>STS</b> 发力、续航与信心</span><span><b>PACE</b> 恢复、睡眠与执行</span><span><b>LOAD</b> 累积疲劳与酸痛</span><span><b>LINK</b> 同伴互动与信任</span><small>均为复合指标，不是底层参数。</small></div></aside>`}
  function wheel(id,value,min,max,label){return `<input class="native-wheel-value" id="${id}" type="number" min="${min}" max="${max}" value="${esc(value)}" tabindex="-1" aria-hidden="true"><div class="number-wheel" role="listbox" tabindex="0" data-input="${id}" data-min="${min}" data-max="${max}" aria-label="${label}">${Array.from({length:max-min+1},(_,i)=>`<div class="number-wheel-item" id="${id}-${min+i}" role="option" data-value="${min+i}" aria-selected="false">${min+i}</div>`).join('')}</div>`}
  function render(){$('dayChip').textContent=gameState?gameDate(gameState.day):'DAY 0';pendingAction='';dialogueRun++;if(!gameState){if(screen==='intro')renderIntro();else if(screen==='card')renderCard();else if(screen==='questions')renderQuestions();else if(screen==='look')renderLook();else if(screen==='inviteGate'||screen==='inviteFeedback')renderInviteGate();else renderPhone()}else renderDay();document.querySelector('.handheld').classList.toggle('phone-mode',isPhone());document.querySelector('.handheld').classList.toggle('mirror-mode',Boolean(gameState&&['reportSelf','weekEnding'].includes(gameState.step)));initWheels();restoreScroll();startDialogue();cancelAnimationFrame(raf);clearTimeout(drawTimer);frame=0;drawLoop();paintMinis();paintGroupPhoto();scrollChat()}
  function renderIntro(){$('game').innerHTML=stage('WEEK 01 / 07:12','你的房间',box('',`<h1>飙肌野郎</h1>${rewound?'<p class="time-echo">又是这一天。购物袋上的折痕，甚至没有换个方向。</p>':''}<p class="lead">前几天去超市买东西，结账后，一张卡被某种神秘力量塞进了手里。<br>也可能只是促销员。自由意志当时忙着找零钱。</p><div class="intro-promo"><strong>57TRAINING</strong><span>七日体验！今天生效！</span><small>命运限时派送 · 解释权暂归前台</small></div><p>手机震了一下。那张卡好像开始履行自己的计划。</p>${button('card','翻出那张体验卡')}`))}
  function renderCard(){$('game').innerHTML=stage('DAY 0 / CHECK IN','前台桌面',box('体验卡','<p>卡片边缘有点粗糙，正面只留了三行空白。</p><div class="form-grid"><label class="field">名字<input id="cardName" maxlength="10" autocomplete="off" value="'+esc(card.name)+'" placeholder="怎么称呼你"></label><label class="field">身高 / cm'+wheel('cardHeight',card.height,120,220,'身高，厘米')+'</label><label class="field">体重 / kg'+wheel('cardWeight',card.weight,30,220,'体重，公斤')+'</label></div><p class="privacy">资料只用于本次游戏，不上传、不保存，刷新/关闭后清除。</p>'+button('questions','把卡递给前台')))}
  function renderQuestions(){const q=START_QUESTIONS[card.question],last=card.answers.at(-1);if(!q){screen='look';render();return}const feedback=last?.question===card.question?box(card.question===3?(card.name||'你'):'57training 前台',`<p class="lead" data-dialogue>${esc(last.line)}</p>${delayedAction(button('questionNext',card.question===3?'去衣柜前看看':'听下一个问题'))}`):box(q.who==='你'?(card.name||'你'):q.who,`<p class="lead" data-dialogue>${esc(q.text)}</p>${selection(q.choices.map(c=>({act:`answer:${c.id}`,label:esc(c.label)})))}`);$('game').innerHTML=stage(`DAY 0 / Q${card.question+1}-04`,card.question<3?'57training 前台':'更衣室门口',feedback)}
  function lookRows(){return Object.entries(APPEARANCE).map(([key,values])=>`<div class="look-row"><button data-act="look-" data-key="${key}" aria-label="上一个选项">‹</button><span class="look-value">${esc(values[card.look[key]])}</span><button data-act="look+" data-key="${key}" aria-label="下一个选项">›</button></div>`).join('')}
  function renderLook(){$('game').innerHTML=stage('DAY 0 / GET DRESSED','衣柜',box(card.name||'你','<p>先穿得像自己。以后会变成什么样，等练完再说。</p><div class="scroll-area" data-scroll-key="look"><div class="look-grid">'+lookRows()+'</div></div><div class="panel-action">'+button('inviteGate','衣服没问题，准备出门')+'</div>','fixed-panel'))}
  function renderInviteGate(){const feedback=screen==='inviteFeedback';$('game').innerHTML=stage('DAY 0 / BEFORE LEAVING','你的房间',box(card.name||'老己',feedback?`<p class="lead" data-dialogue>${inviteDecision?'一个群不一定能把人叫齐，但能把饭店地址放在同一个地方。':'今天就自己练。少协调几句，也给自己留一点安静。'}</p>${delayedAction(button(inviteDecision?'phone':'startDay',inviteDecision?'拿起手机，建个群':'关上门，出发'))}`:`<p class="lead" data-dialogue>要不要叫几个人一起？一个人去，也完全说得通。</p>${selection([{act:'invite:yes',label:'建个小群，问问谁有空'},{act:'invite:no',label:'今天自己练'}])}`))}
  function renderPhone(){const chosen=selected.length+(custom?1:0);if(invitesSent){const replies={xixi:'收到。先别急着上重量。',feifei:'行，练完再解决吃什么这个大问题。',y:'看到了。能赶上就来，不用等我。',meng:'好，我下班看看。你先按自己的节奏来。',deng:'你们练。吃饭的地址晚点发我。',dai:'有感觉吗？我是说这个群名。',kevin:'可以。时间地点发这里。',mystery:'行。先问一下，空调吹哪边。'};$('game').innerHTML=stage('','',box('',`<p class="chat-system">你创建了群聊「先试试」</p><p class="chat-system">你邀请了${[...selected.map(id=>contacts.find(p=>p.id===id)?.name),custom?.name].filter(Boolean).map(esc).join('、')}加入聊天。</p>${chatBubble(card.name.trim()||'老己','群先建着，有空就来。不用每天报到。',true,'p0')}${selected.map(id=>chatBubble(contacts.find(p=>p.id===id).name,replies[id],false,id)).join('')}${custom?chatBubble(custom.name,'收到，有空就碰头。'):''}<p class="chat-system" data-dialogue>消息已送达。</p>${delayedAction(button('startDay','收起手机，出发'))}`));return}
    $('game').innerHTML=stage('DAY 0 / 07:24','像素手机',box('选择群成员','<p class="chat-system">选择好友加入群聊</p><div class="scroll-area" data-scroll-key="phone"><div class="contact-list">'+contacts.map(p=>`<button class="contact" data-act="contact" data-id="${p.id}" aria-pressed="${selected.includes(p.id)}"><canvas class="mini-sprite" width="16" height="16" data-mini="${p.id}"></canvas><span><b>${esc(p.name)}</b><small>${esc(p.relation)}</small></span><span class="tick">${selected.includes(p.id)?'✓':'□'}</span></button>`).join('')+'</div>'+(custom?customFriendForm():button('addFriend','＋ 添加好友'))+`</div><p class="party-line panel-foot">${chosen?'已选：'+[...selected.map(id=>contacts.find(x=>x.id===id)?.name),custom?.name].filter(Boolean).map(esc).join('、'):'尚未选择好友'}</p><div class="panel-action">`+button('sendInvites',`创建群聊（${chosen+1}）`,chosen?'':'disabled')+'</div>','fixed-panel'))}
  function customFriendForm(){return `<div class="custom-friend"><div class="form-grid"><label class="field">好友昵称<input id="friendName" maxlength="10" value="${esc(custom.name)}"></label><label class="field">备注<input id="friendRelation" maxlength="16" value="${esc(custom.relation)}"></label></div><div class="custom-focus"><button data-act="friendRandom">换一个推荐</button><button data-act="friendRemove">取消添加</button></div></div>`}
  function foodLabel(store){if(store==='几丁质功能饮料自动贩卖机')return '游戏内虚构配方 · 取货口在下方';const familiar=gameState.stores[store]||0;return familiar>1?'店员已经开始省略菜单介绍。':familiar?'上次来过，店员似乎记得你。':'第一次进这家店。'}
  function bar(label,value){const width=Math.max(12,Math.min(100,value*20));return `<div class="result-row"><span>${label}</span><i><b style="width:${width}%"></b></i><strong>${metricWord(value,label==='累积负荷')}</strong></div>`}
  function endingProfile(state){return paymentProfile(state).name}
  function thoughtLines(state){const m=compositeMetrics(state),key=m.fatigue>=4?'rest':Object.keys(state.stores).length>=5?'food':state.traits.social+state.traits.trust>=6?'social':state.traits.discipline>=4?'ritual':'body';return [key,'self',key==='body'?'ritual':'body'].map((k,i)=>MIRROR_POOLS[k][hash(`${state.seed}:mirror:${k}:${i}`)%MIRROR_POOLS[k].length])}
  function inboxButton(act,icon,title,preview,key){const seen=gameState.reportViewed.includes(key);return `<button type="button" class="message-entry${seen?' is-read':''}" data-act="${act}"><span class="message-icon">${icon}</span><span><b>${title}</b><small>${preview}</small></span><i>${seen?'READ':'NEW'}</i></button>`}
  function chatBubble(name,line,out=false,id=''){return `<div class="chat-line ${out?'from-self':''}">${id?`<canvas class="chat-avatar" width="16" height="16" data-mini="${esc(id)}"></canvas>`:''}<div><small>${esc(name)}</small><div class="chat-bubble ${out?'outgoing':''}"><p>${esc(line)}</p></div></div></div>`}
  function messageList(){return `<div class="pixel-phone-list">${inboxButton('open:gym','57','57training','重磅！你的七日潜力报告已出炉！','gym')}${inboxButton('open:pay','¥','57pay · 公众号','支付通知及本周账单','pay')}${inboxButton('open:friend','▦',esc(gameState.groupName),gameState.party.length>1?'群里有人提起这一周':'一条留给自己的打卡记录','friend')}</div>`}
  function renderReport(step){const m=compositeMetrics(gameState),h=gameState.party[0].hidden,total=gameState.spend.reduce((sum,item)=>sum+item.price,0);
    if(step==='lockscreen')return box('',`<div class="lock-wallpaper"><canvas data-group-photo width="240" height="160" aria-label="本周实际同行者的像素合照"></canvas><div class="lock-caption"><span>◈</span><h1 class="phone-now">${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</h1><p>本周合影 · 留在屏幕上</p></div></div><div class="lock-notices">${messageList()}</div><p class="chat-system">点按通知，打开聊天</p>`);
    if(step==='inbox'){const seen=['gym','pay','friend'].every(x=>gameState.reportViewed.includes(x));return box('',`${messageList()}${seen?button('reportSelf','按灭屏幕，安静一会儿'):'<p class="chat-system">消息都在这里，不急着回复。</p>'}`)}
    if(step==='reportGym')return box('已关注 · 服务通知',`${chatBubble('57training','恭喜！你已解锁「连续到场的人」这一稀有身份！') }<article class="ad-report"><small>会员潜力特别企划 / WEEK 01</small><h2>七天！见证你的<br>巨大潜力！！</h2><p class="ad-stamp">专属报告 · 限时心动</p><div class="result-bars">${bar('训练状态',m.drive)}${bar('恢复节奏',m.rhythm)}${bar('累积负荷',m.fatigue)}${bar('同行默契',m.connection)}</div><p>${h.sessions.length>=16?'计划外加练已被我们敏锐捕捉！这份热情值得更大的储物柜！':'每次踏进大门，都是一次惊人的刷卡成功！你的动作正在找到自己的节奏。'}</p><p>${m.fatigue>=4?'温馨提醒：恢复也是实力。今天先休息，优惠短信替你继续发力。':'恭喜维持住自己的节奏！比起追逐重量，动作稳定更值得保留。'}</p><h3>现在续卡！赠送动作评估！</h3><p>下周的你，值得本周的优惠！错过今天——明天可能还会收到，但今天这条只发一次！</p><small>游戏内广告；无购买入口。训练循序渐进，身体变化不作承诺。</small></article>${chatBubble('57training','不用立刻回复。我们已经替你把“考虑一下”加入销售漏斗。')}`);
if(step==='reportPay')return box('57pay · 周度观察',`<article class="payment-card weekly-card"><small>公众号推送 · 周度小结</small><h2>${endingProfile(gameState)}</h2><p>本周合计 ¥${total} · ${gameState.spend.length} 笔</p><p>你在 ${Object.keys(gameState.stores).length} 个吃饭地点留下记录。</p><p>${esc(paymentProfile(gameState).line)}</p><small>此画像由账单擅自总结，不负责解释你。</small></article><p class="chat-system">已关注公众号 · 最近消息在上</p>${gameState.spend.slice().reverse().map((item,i)=>`<p class="chat-system">DAY ${item.day} · ${['meal','side'].includes(item.kind)?'饭点':'训练时段'}</p><article class="payment-card"><small>57pay · 支付通知</small><h3>支付成功</h3><strong>¥${item.price}</strong><p>收款方：${esc(item.store)}</p><p>商品：${esc(item.name)}</p><footer>已完成 · 记入本周账单</footer></article>`).join('')}`);
    if(step==='reportFriend'){const members=gameState.party,messages=friendEndingMessages(gameState),replies=gameState.groupReplies||[],options=GROUP_REPLIES.filter(r=>!replies.includes(r.id)).sort((a,b)=>hash(`${seed}:reply:${a.id}`)-hash(`${seed}:reply:${b.id}`)).slice(0,3);return box('',`<p class="chat-system">${esc(gameState.groupName)}（${members.length}） · ${members.map(p=>esc(p.name)).join('、')}</p><p class="chat-system">七天前 · ${members.length>1?'你创建了群聊':'仅自己可见的打卡记录'}</p>${chatBubble(members[0].name,members.length>1?'群先建着，有空就来。不用每天报到。':'先给这一周留个位置。',true,members[0].id)}<p class="chat-system">今天 · 体验周结束</p>${messages.length?Array.from({length:Math.max(...messages.map(v=>v.line.split(/(?<=[。？！])/).filter(t=>t.trim()).length))},(_,i)=>messages.map(v=>{const parts=v.line.split(/(?<=[。？！])/).filter(t=>t.trim());return parts[i]?chatBubble(v.name,parts[i].trim(),false,v.id):''}).join('')).join(''):chatBubble(members[0].name,'七天都到了。没有群体见证，也算数。',true,members[0].id)}${replies.map(id=>{const r=GROUP_REPLIES.find(v=>v.id===id),p=members[1],ack=p?(GROUP_ACK[p.id]||[r.ack])[hash(`${seed}:${id}`)%((GROUP_ACK[p.id]||[r.ack]).length)]:r.ack;return chatBubble(members[0].name,r.text,true,members[0].id)+(p?chatBubble(p.name,r.ack,false,p.id)+(ack!==r.ack?chatBubble(p.name,ack,false,p.id):''):'<p class="chat-system">已记下。没有人催你回复。</p>')}).join('')}${replies.length?'<p class="chat-system" data-dialogue>消息已送达。群暂时安静了一会儿。</p>':''}${replies.length<3?selection(options.map(r=>({act:'groupReply:'+r.id,label:esc(r.text)})),'chat-replies'):'<p class="chat-system">没有更多话要说，也可以留着这个群。</p>'}`)}
    if(step==='reportSelf'){const lines=thoughtLines(gameState);return `<div class="mirror-glass"><span class="mirror-label">SCREEN OFF / STILL HERE</span><div class="mirror-thoughts">${lines.map(line=>`<p data-dialogue>${esc(line)}</p>`).join('')}</div>${delayedAction(button('weekEnding','再站一会儿'))}</div>`}
    return `<div class="mirror-glass"><div class="mirror-thoughts"><p data-dialogue>屏幕没有再亮。倒影还在。</p><p data-dialogue>明天的事，明天再说。</p></div><div class="credits">WEEK 01 COMPLETE</div>${delayedAction(button('again','回到七天前'))}</div>`
  }
  function renderDay(){const s=gameState.step,day=gameState.day,party=gameState.party,names=attendance(gameState).map(p=>p.name).join('、');let html='';
    if(s==='warmup'){const choices=WARMUPS[day-1],moment=companionMoment(gameState,'train');html=box(day===1?'57training 前台':'训练搭子',`<p class="lead" data-dialogue>${day===1?'“卡给我。先别急着练。”':'“今天先怎么热身？”'}</p>${moment?`<p class="companion-note">${esc(moment)}</p>`:''}${selection(choices.map(c=>({act:`warm:${c.id}`,label:esc(c.label)})),'',`<p class="party-line">今天到场：<strong>${esc(names)}</strong></p>`)}`)}
    else if(s==='warmupResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('toEvent','活动开了。往里走。'))}`);
    else if(s==='event'){const e=eventFor(gameState.seed,day);html=box(e.who,`<p class="lead" data-dialogue>${esc(e.text)}</p>${selection(e.choices.map(c=>({act:`event:${c.id}`,label:esc(c.label)})))}`)}
    else if(s==='eventResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('toWorkout','开始第一段正式训练'))}`);
    else if(s==='workout')html=box(gameState.round===2?'今日大爆发':'巡场教练',`<p class="lead" data-dialogue>${gameState.round===0?'“第一段先把动作做稳。”':gameState.round===1?'“歇够了，换一项继续。”':'“多出来的这一回合，只选你真想做的。”'}</p>${selection(workoutsFor(seed,day,gameState.round).map(id=>{const w=WORKOUTS[id];return {act:`work:${id}`,label:`<b>${esc(w.name)}</b><span>${esc(w.explain)}</span>`}}),'workout-list')}`);
    else if(s==='workoutResult')html=box(party[0].name,`<p class="watch-copy" data-dialogue>你抬起手腕。四项可读指标重新组合了一次。</p><p data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('afterWorkout',gameState.round===1?'去喝水，看看场内发生了什么':'让手表决定下一段'))}`);
    else if(s==='gymEvent'){const e=gymEventFor(gameState.seed,day,gameState);html=box(e.who,`<p class="lead" data-dialogue>${esc(e.text)}</p>${selection(e.choices.map(c=>({act:`gym:${c.id}`,label:esc(c.label)})))}`)}
    else if(s==='gymEventResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('toWorkout','继续第二段训练'))}`);
    else if(s==='bonusOffer')html=box('运动手表',`<p class="lead" data-dialogue>今天的综合状态还有余裕。要不要把它换成一段计划外训练？</p>${selection([{act:'bonus:go',label:'今天大爆发：再练一回合'},{act:'bonus:stop',label:'把余裕留给恢复和晚饭'}])}`);
    else if(s==='bonusResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('afterBonus',gameState.last.id==='go'?'选择额外训练':'去吃饭'))}`);
    else if(s==='mealPlace'){const stores=storesFor(gameState.seed,day,gameState),moment=companionMoment(gameState,'meal');html=box('57training 门外',`<p class="lead" data-dialogue>训练结束。街灯刚亮，先决定往哪边走。</p>${moment?`<p class="companion-note">${esc(moment)}</p>`:''}${selection(stores.map(store=>({act:`store:${store}`,label:`<b>${esc(store)}</b><span>${esc(STORE_LINES[store])}</span>`})),'store-choices')}`)}
    else if(s==='mealPlaceResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('toMenu',gameState.selectedStore==='几丁质功能饮料自动贩卖机'?'走向健身房外的自动贩卖机':`推门进入 ${esc(gameState.selectedStore)}`))}`)
    else if(s==='meal'){const store=gameState.selectedStore;html=box(store,`<p class="lead" data-dialogue>${esc(STORE_LINES[store])}</p>${selection(menuFor(gameState.seed,day,store).map(item=>({act:`meal:${store}|${item.id}`,disabled:item.soldOut,label:`<span class="food-pixel food-${esc(item.icon)}" aria-hidden="true"></span><span class="food-copy"><b>${esc(item.name)}${item.soldOut?' · 售罄':''}</b><small>¥${item.price} · ${esc(foodLabel(store))}</small></span>`})),'food-choices')}`)}
    else if(s==='mealResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('afterMeal','把最后一口吃完'))}`);
    else if(s==='sideOffer'){const side=sideFor(gameState);html=box('店员',`<p class="lead" data-dialogue>“还要不要加一份${esc(side.name)}？今天刚好有。”</p>${selection([{act:'side:yes',label:`加一份 · ¥${side.price}`},{act:'side:no',label:'这顿够了，谢谢'}])}`)}
    else if(s==='sideResult')html=box('',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('afterMeal','慢慢收尾'))}`);
    else if(s==='afterEvent'){const e=afterEventFor(gameState.seed,day,gameState);html=box(e.who,`<p class="lead" data-dialogue>${esc(e.text)}</p>${selection(e.choices.map(c=>({act:`after:${c.id}`,label:esc(c.label)})))}`)}
    else if(s==='afterEventResult')html=box('旁白',`<p class="lead" data-dialogue>${esc(gameState.last.line)}</p>${delayedAction(button('finishDay','让今天慢慢结束'))}`);
    else if(s==='summary')html=box(party[0].name,`<div class="day-end"><p>洗完澡以后，今天的动作和晚饭一起留在身体里。</p><p>${compositeMetrics(gameState).fatigue>=4?'明天也许该对恢复认真一点。':'下楼时，脚步比早上稳了一点。'}</p></div>${button('nextDay',day===7?'关上第七天的储物柜':'睡一觉，进入 DAY '+(day+1))}`);
    else if(s==='epilogue'){const lines=epilogueLines(gameState);html=box(party[0].name,`<div class="monologue"><p data-dialogue>${esc(lines[0])}</p>${lines.slice(1).map(line=>`<p data-dialogue>${esc(line)}</p>`).join('')}<p data-dialogue>口袋里传来很廉价的震动声。手机弹出几个消息。</p></div>${delayedAction(button('lockscreen','看看锁屏'))}`)}
    else html=renderReport(s);
    if(['mealResult','gymEventResult','sideResult'].includes(s)){const last=gameState.spend.at(-1);if(last?.day===day&&(s==='mealResult'&&last.kind==='meal'||s==='gymEventResult'&&last.kind==='gym'||s==='sideResult'&&last.kind==='side'&&gameState.last.id==='yes'))html=`<aside class="payment-toast" role="status">57pay · 公众号<br>支付成功 ¥${last.price} · ${esc(last.store)}</aside>`+html}
    const labels={warmup:'WARM UP',warmupResult:'FEEDBACK',event:'DAILY EVENT',eventResult:'FEEDBACK',workout:'57TRAINING',workoutResult:'WRIST WATCH',gymEvent:'GYM EVENT',gymEventResult:'FEEDBACK',bonusOffer:'EXTRA ROUND',bonusResult:'FEEDBACK',mealPlace:'STREET',mealPlaceResult:'ARRIVAL',meal:'ORDER',mealResult:'FEEDBACK',afterEvent:'NIGHT EVENT',afterEventResult:'FEEDBACK',summary:'DAY END',epilogue:'CLOSING',inbox:'MESSAGES',reportGym:'57TRAINING',reportPay:'PAY',reportFriend:'FRIEND',reportSelf:'INNER VOICE',weekEnding:'WEEK END'},scene=sceneName(),place=scene.startsWith('store-')?gameState.selectedStore:scene.startsWith('outside')?'57training 门外':scene==='gym'||scene==='warmup'||scene==='gym-side'||scene==='watch'?'57training':scene==='phone'?'像素手机':'你的房间';$('game').innerHTML=stage(`${gameDate(day)} / ${labels[s]||'DINNER'}`,place,html)
  }
  function initWheels(){document.querySelectorAll('.number-wheel').forEach(wheel=>{const input=$(wheel.dataset.input),min=Number(wheel.dataset.min),max=Number(wheel.dataset.max),row=Number.parseFloat(getComputedStyle(wheel).getPropertyValue('--wheel-row'))||22;let selected=null,ticking=false;const sync=value=>{const next=Math.max(min,Math.min(max,value));if(selected)selected.setAttribute('aria-selected','false');selected=wheel.querySelector(`[data-value="${next}"]`);selected?.setAttribute('aria-selected','true');if(selected)wheel.setAttribute('aria-activedescendant',selected.id);if(input&&input.value!==String(next)){input.value=String(next);input.dispatchEvent(new Event('input',{bubbles:true}))}};const syncScroll=()=>sync(min+Math.round(wheel.scrollTop/row));wheel.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false;syncScroll()})});wheel.addEventListener('click',event=>{const item=event.target.closest('.number-wheel-item');if(item)wheel.scrollTo({top:(Number(item.dataset.value)-min)*row,behavior:'smooth'})});wheel.addEventListener('keydown',event=>{const keys={ArrowUp:-1,ArrowDown:1,PageUp:-5,PageDown:5};if(!(event.key in keys))return;event.preventDefault();const value=Math.max(min,Math.min(max,Number(input.value)+keys[event.key]));wheel.scrollTo({top:(value-min)*row,behavior:'smooth'});sync(value)});const value=Math.max(min,Math.min(max,Number(input?.value)||min));wheel.scrollTop=(value-min)*row;sync(value)})}
  function restoreScroll(){requestAnimationFrame(()=>document.querySelectorAll('.scroll-area[data-scroll-key]').forEach(area=>{area.scrollTop=scrollPositions[area.dataset.scrollKey]||0}))}
  function startDialogue(){const root=$('game'),lines=[...root.querySelectorAll('[data-dialogue]')],actions=root.querySelector('.dialogue-actions');if(!actions)return;if(!lines.length){actions.hidden=false;actions.classList.add('is-ready');return}const run=dialogueRun,reduce=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;const reveal=()=>{if(run!==dialogueRun)return;actions.hidden=false;actions.classList.add('is-ready');scrollChat();announce('选项已出现')};if(reduce){reveal();return}const full=lines.map(line=>line.textContent);lines.forEach(line=>line.textContent='');let lineIndex=0,charIndex=0;const tick=()=>{if(run!==dialogueRun)return;const line=lines[lineIndex],text=full[lineIndex];if(charIndex<text.length){const char=text[charIndex++];line.textContent=text.slice(0,charIndex);setTimeout(tick,/[。！？…，；：]/.test(char)?72:28);return}lineIndex++;charIndex=0;if(lineIndex<lines.length){setTimeout(tick,gameState&&['reportSelf','weekEnding'].includes(gameState.step)?650:110);return}setTimeout(reveal,220)};setTimeout(tick,70)}
  function saveInputs(){const n=$('cardName'),h=$('cardHeight'),w=$('cardWeight');if(n)card.name=n.value;if(h)card.height=h.value;if(w)card.weight=w.value;const fn=$('friendName'),fr=$('friendRelation');if(custom&&fn){custom.name=fn.value||custom.name;custom.relation=fr.value||custom.relation}}
  function startAnimation(next,ms=1050){animating=true;$('game').querySelectorAll('button').forEach(b=>b.disabled=true);setTimeout(()=>{animating=false;next();render()},ms)}
  document.addEventListener('input',saveInputs);
  document.addEventListener('scroll',event=>{const area=event.target.closest?.('.scroll-area[data-scroll-key]');if(area)scrollPositions[area.dataset.scrollKey]=area.scrollTop},true);
  document.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b||b.disabled||animating)return;saveInputs();let a=b.dataset.act;
    if(a==='watchHelp'){const watch=b.closest('.sport-watch'),legend=watch?.querySelector('.watch-legend'),open=Boolean(legend?.hidden);if(legend)legend.hidden=!open;b.setAttribute('aria-expanded',String(open));return}
    if(a==='selectChoice'){const panel=b.closest('.dialogue-actions');panel?.querySelectorAll('.select-option').forEach(choice=>choice.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');pendingAction=b.dataset.choice||'';const confirmButton=panel?.querySelector('.confirm-choice');if(confirmButton)confirmButton.disabled=!pendingAction;announce('已选择：'+b.textContent.trim());return}
    if(a==='confirmChoice'){if(!pendingAction)return;a=pendingAction}
    if(a==='restart'){if(confirm('从 DAY 0 重新开始？本次进度会立即清除。'))resetWeek();return}if(a==='card'||a==='questions'||a==='look'||a==='phone'||a==='inviteGate'){screen=a;render();return}
    if(a.startsWith('answer:')){const q=START_QUESTIONS[card.question],choice=q?.choices.find(c=>c.id===a.slice(7));if(!choice)return;card.points=card.points.map((v,i)=>v+(choice.points[i]||0));for(const [key,value] of Object.entries(choice.delta||{})){if(['sleep','mood','fuel'].includes(key))card.needs[key]=(card.needs[key]||0)+value;else card.traits[key]=(card.traits[key]||0)+value}card.tags.push(...choice.tags);card.answers.push({question:card.question,id:choice.id,line:choice.line});render();return}
    if(a==='questionNext'){card.question++;if(card.question>=START_QUESTIONS.length)screen='look';render();return}
    if(a==='point-'||a==='point+'){const i=Number(b.dataset.index),sum=card.points.reduce((x,y)=>x+y,0);if(a==='point-'&&card.points[i]>1)card.points[i]--;if(a==='point+'&&card.points[i]<4&&sum<6)card.points[i]++;render();return}
    if(a==='look-'||a==='look+'){const key=b.dataset.key,n=APPEARANCE[key].length;card.look[key]=(card.look[key]+(a==='look+'?1:-1)+n)%n;render();return}
    if(a==='contact'){const id=b.dataset.id;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length+(custom?1:0)<3)selected.push(id);else announce('最多添加三位好友');render();return}
    if(a==='addFriend'){if(selected.length>=3){announce('群里已经有四个人了');return}custom=randomFriend(seed,3);custom._points=[2,2,2];render();return}if(a==='friendRandom'){const nextSeed=randomSeed();custom=randomFriend(nextSeed,3);custom._points=[1,1,1];for(let n=0;n<3;n++){let i=hash(`${nextSeed}:point:${n}`)%3;while(custom._points[i]>=4)i=(i+1)%3;custom._points[i]++}render();return}if(a==='friendRemove'){custom=null;render();return}
    if(a==='friendPoint-'||a==='friendPoint+'){const i=Number(b.dataset.index),sum=custom._points.reduce((x,y)=>x+y,0);if(a==='friendPoint-'&&custom._points[i]>1)custom._points[i]--;if(a==='friendPoint+'&&custom._points[i]<4&&sum<6)custom._points[i]++;render();return}
    if(a==='invite:yes'||a==='invite:no'){inviteDecision=a==='invite:yes';if(!inviteDecision){selected=[];custom=null}screen='inviteFeedback';render();return}
    if(a==='sendInvites'||a==='editInvites'){if(a==='sendInvites'&&!selected.length&&!custom)return;invitesSent=a==='sendInvites';render();return}
    if(a==='startDay'){const self={name:card.name.trim()||'老己',height:card.height,weight:card.weight,points:card.points,look:card.look,relation:'你自己'},specs=[self,...selected.map(id=>contacts.find(x=>x.id===id)).filter(Boolean).map(p=>p.profile||{name:p.name,relation:p.relation,look:p.look,focus:dominantFocus(p)}),...(custom?[{name:custom.name,relation:custom.relation,look:custom.look,points:custom._points}]:[])];gameState=createGame(seed,specs,{traits:card.traits,needs:card.needs,tags:card.tags});screen='day';startAnimation(()=>{},850);return}
    if(a.startsWith('warm:')){startAnimation(()=>{gameState=chooseWarmup(gameState,a.slice(5))});return}if(a==='toEvent'){gameState=continueToEvent(gameState);render();return}if(a.startsWith('event:')){startAnimation(()=>{gameState=chooseEvent(gameState,a.slice(6))});return}if(a==='toWorkout'){gameState=continueToWorkout(gameState);render();return}if(a.startsWith('work:')){startAnimation(()=>{gameState=doWorkout(gameState,a.slice(5))},760);return}if(a==='afterWorkout'){gameState=continueAfterWorkout(gameState);render();return}if(a.startsWith('gym:')){startAnimation(()=>{gameState=chooseGymEvent(gameState,a.slice(4))});return}if(a.startsWith('bonus:')){gameState=chooseBonus(gameState,a.slice(6));render();return}if(a==='afterBonus'){gameState=continueAfterBonus(gameState);render();return}if(a.startsWith('store:')){startAnimation(()=>{gameState=chooseStore(gameState,a.slice(6))},620);return}if(a==='toMenu'){gameState=continueToMenu(gameState);render();return}if(a.startsWith('meal:')){gameState=chooseMeal(gameState,a.slice(5));render();return}if(a.startsWith('side:')){gameState=chooseSide(gameState,a.slice(5));render();return}if(a==='afterMeal'){gameState=continueAfterMeal(gameState);render();return}if(a.startsWith('after:')){startAnimation(()=>{gameState=chooseAfterEvent(gameState,a.slice(6))});return}if(a==='finishDay'){gameState=continueAfterEvent(gameState);render();return}if(a==='nextDay'){gameState=advanceDay(gameState);render();return}if(a==='lockscreen'||a==='inbox'||a==='reportSelf'||a==='weekEnding'){gameState={...gameState,step:a==='lockscreen'&&gameState.phoneUnlocked?'inbox':a};render();return}if(a.startsWith('open:')){const key=a.slice(5),step={gym:'reportGym',pay:'reportPay',friend:'reportFriend'}[key];gameState={...gameState,step,phoneUnlocked:true,reportViewed:[...new Set([...gameState.reportViewed,key])]};render();return}
    if(a.startsWith('groupReply:')){const id=a.slice(11);if(!GROUP_REPLIES.some(r=>r.id===id)||(gameState.groupReplies||[]).includes(id))return;gameState={...gameState,groupReplies:[...(gameState.groupReplies||[]),id]};render();return}
    if(a==='again'){resetWeek();return}
  });
  function resetWeek(){cancelAnimationFrame(raf);clearTimeout(drawTimer);dialogueRun++;seed=randomSeed();gameState=null;screen='intro';animating=false;pendingAction='';invitesSent=false;inviteDecision=false;selected=[];custom=null;rewound=true;card={name:'',height:'153',weight:'43',points:[1,1,1],look:defaultLook(seed,0),question:0,answers:[],traits:{},needs:{},tags:[]};contacts=presetContacts(seed);for(const key of Object.keys(scrollPositions))delete scrollPositions[key];render()}
  function dominantFocus(p){return ['strength','cardio','mobility'].sort((a,b)=>p.hidden[b]-p.hidden[a])[0]}
  function paintMinis(){document.querySelectorAll('[data-mini]').forEach(c=>{const p=[...contacts,...currentParty()].find(x=>x.id===c.dataset.mini);if(p)drawMini(c.getContext('2d'),p,3,14,0,'idle',1)})}
  function scrollChat(){if(gameState?.step==='reportFriend')requestAnimationFrame(()=>{const panel=document.querySelector('.chat-screen > .box');if(panel)panel.scrollTop=panel.scrollHeight})}
function paintGroupPhoto(){const c=document.querySelector('[data-group-photo]');if(!c)return;const x=c.getContext('2d'),party=gameState.party.filter((p,i)=>i===0||p.hidden.sessions.length||Object.keys(p.hidden.meals).length);rect(x,'#6c795f',0,0,240,160);rect(x,'#b7c6a5',12,12,216,112);rect(x,'#333b3d',0,124,240,36);party.forEach((p,i)=>drawMini(x,p,105+(i-(party.length-1)/2)*(party.length===4?49:58),118,0,'idle',3));}
  function drawLoop(){const canvas=$('stage');if(!canvas)return;drawScene(canvas.getContext('2d'),sceneName(),frame,currentParty());frame=(frame+1)%4;raf=requestAnimationFrame(()=>{drawTimer=setTimeout(drawLoop,animating?170:520)})}
  function rect(x,c,px,py,w,h){x.fillStyle=c;x.fillRect(px,py,w,h)}
  function drawMini(x,p,px,ground,f,action='idle',scale=2){const L=p.look||defaultLook(1,0),skin=['#f0c39b','#b97858','#8c533d','#f2d1b1'][(L.eyes+L.body)%4],hair=['#2b2531','#6c4438','#c7c6bd','#a33c58','#326b82'][L.hairColor%5],tops=['#e26d78','#697ab3','#f0c85c','#5d927b','#eee3bf','#252431','#50757c','#353b44','#89748a'],bottoms=['#3d4265','#486967','#8f5e80','#d8a967','#333846','#292936','#72545e'],shoe=['#eee3bf','#25283a','#b74b5a','#6d5d84'][L.shoes%4],bob=f%2&&action!=='watch'?scale:0,wide=p.appearanceMark==='power'?scale:0;rect(x,hair,px+3*scale,ground-13*scale+bob,4*scale,3*scale);if(L.hair===2||L.hair===3||L.hair===5)rect(x,hair,px+2*scale,ground-11*scale+bob,6*scale,5*scale);rect(x,skin,px+3*scale,ground-11*scale+bob,4*scale,4*scale);rect(x,tops[L.top%tops.length],px+2*scale-wide,ground-7*scale+bob,6*scale+wide*2,5*scale);if(p.appearanceMark==='power')rect(x,skin,px,ground-6*scale+bob,2*scale,4*scale);else{rect(x,skin,px+scale,ground-6*scale+bob,scale,4*scale);rect(x,skin,px+8*scale,ground-6*scale+bob,scale,4*scale)}rect(x,bottoms[L.bottom%bottoms.length],px+2*scale,ground-2*scale+bob,3*scale,3*scale);rect(x,bottoms[L.bottom%5],px+6*scale,ground-2*scale+bob,2*scale,3*scale);const step=f%2&&action!=='watch'?scale:0;rect(x,shoe,px+2*scale-step,ground+scale,3*scale,scale);rect(x,shoe,px+6*scale+step,ground+scale,3*scale,scale);if(L.accessory===1)rect(x,'#28304b',px+3*scale,ground-10*scale+bob,4*scale,scale);if(L.accessory===4||p.appearanceMark==='runner')rect(x,'#edc75e',px+2*scale,ground-12*scale+bob,6*scale,scale);if(L.top===5)rect(x,'#dbd1bc',px+4*scale,ground-6*scale+bob,2*scale,2*scale);if(L.top===6)rect(x,'#f1e9cb',px+4*scale,ground-7*scale+bob,scale,4*scale);if(L.top===7)rect(x,'#839e9b',px+5*scale,ground-7*scale+bob,scale,5*scale);if(L.top===8)for(let j=0;j<3;j++)rect(x,'#302a37',px+2*scale,ground-(7-j*2)*scale+bob,6*scale,scale);if(L.bottom===5)rect(x,'#bec3bc',px+2*scale,ground-scale,6*scale,scale);if(L.bottom===6)for(let j=0;j<3;j++)rect(x,'#c29b92',px+(2+j*2)*scale,ground-2*scale,scale,3*scale);if(L.accessory>=6)rect(x,'#c9d8d0',px+(L.accessory===7?8:3)*scale,ground-(L.accessory===7?9:6)*scale+bob,2*scale,scale);if(L.shoes===4){rect(x,'#171922',px+2*scale,ground,3*scale,3*scale);rect(x,'#171922',px+6*scale,ground,3*scale,3*scale)}if(action==='watch')rect(x,'#73c2bf',px+9*scale,ground-5*scale,2*scale,2*scale)}
  function drawScene(x,scene,f,party){x.imageSmoothingEnabled=false;x.clearRect(0,0,240,160);const sky=['room','bedroom','locker','desk'].includes(scene)?'#65658a':scene==='outside-night'?'#34364f':'#8bc4b8';rect(x,sky,0,0,240,160);
    if(scene==='gym'||scene==='gym-side'||scene==='warmup'){rect(x,'#d8e9c4',0,52,240,108);rect(x,'#59647a',0,118,240,42);for(let i=0;i<6;i++)rect(x,'#4b5368',i*44,118,2,42);if(scene==='warmup'){rect(x,'#8b7185',18,92,70,12);rect(x,'#e56b88',24+(f%2)*4,88,28,3);rect(x,'#65c3bd',134,88,62,4)}else if(scene==='gym-side'){for(let i=0;i<4;i++)rect(x,'#34384f',20+i*50,70,34,4);rect(x,'#f3ca67',25+(f%2)*3,66,9,4);rect(x,'#65c3bd',184,52,5,58)}else{rect(x,'#34384f',18,28,4,90);rect(x,'#34384f',20,28,52,4);rect(x,'#e56b88',180,66,34+(f%2)*3,4);rect(x,'#34384f',187,70,4,48);rect(x,'#34384f',207,70,4,48)}party.forEach((p,i)=>drawMini(x,p,24+i*(party.length===4?44:64),112,f,animating?'move':'idle',2))}
    else if(scene==='outside'||scene==='outside-night'){rect(x,scene==='outside-night'?'#535777':'#a7cbb1',0,0,240,112);rect(x,'#2f3147',0,112,240,48);rect(x,'#824f67',15,35,88,77);rect(x,'#f3ca67',28,48,62,18);rect(x,'#202339',36,54,46,5);rect(x,'#4c5368',132,68,96,44);for(let i=0;i<3;i++)rect(x,['#e56b88','#65c3bd','#f3ca67'][i],142+i*28,76,20,11);rect(x,'#f3ca67',218,30,3,82);rect(x,'#f3ca67',210,28,19,5);if(f%2)rect(x,'#f8f0c8',205,36,6,3);party.forEach((p,i)=>drawMini(x,p,22+i*(party.length===4?44:64)+(animating?f*2:0),108,f,'move',2))}
    else if(scene.startsWith('store-')){rect(x,'#f2d59a',0,38,240,122);rect(x,'#87566d',0,116,240,44);if(scene==='store-fastfood'){rect(x,'#ab3d4f',8,20,224,25);x.fillStyle='#f7d76d';x.font='bold 12px monospace';x.fillText('dx',18,37);for(let i=0;i<3;i++){rect(x,'#f7e9b9',75+i*48,26,40,13);rect(x,'#d29348',82+i*48,29,24,5)}rect(x,'#b8474d',8,84,224,22);rect(x,'#f5cf65',8,79,224,5);rect(x,'#36384c',176,64,24,15);rect(x,'#a5d4ba',180,67,16,7)}else if(scene==='store-vending'){rect(x,'#34384f',72,22,96,96);for(let y=35;y<92;y+=18)for(let i=0;i<4;i++)rect(x,['#65c3bd','#e56b88','#f3ca67','#75a765'][(i+y)%4],82+i*19,y,10,13);rect(x,'#f8f0c8',142,96,14,7)}else if(scene==='store-bakery'||scene==='store-convenience'){rect(x,'#5c435c',12,22,72,82);for(let y=36;y<94;y+=18)rect(x,'#f4e3b2',18,y,60,5);for(let i=0;i<3;i++)rect(x,['#f3ca67','#d68d5d','#f8f0c8'][i],22+i*18,29+(f%2),12,7);rect(x,'#3b4156',108,75,116,8);rect(x,'#65c3bd',130,61,22,14)}else{rect(x,'#5c435c',10,28,52,71);rect(x,'#3b4156',86,76,138,8);rect(x,'#f8f0c8',106,66,32,9);rect(x,'#f3ca67',171,62,24,13);rect(x,'#e56b88',22,35+(f%2)*2,28,4)}party.forEach((p,i)=>drawMini(x,p,24+i*(party.length===4?44:64),113,f,'idle',2))}
    else if(scene==='watch'){rect(x,'#27283d',0,0,240,160);rect(x,'#bd926e',46,70,148,34);rect(x,'#222538',92,45,58,72);rect(x,'#65c3bd',98,51,46,60);rect(x,'#1e2634',103,56,36,50);const dots=f%4+4;for(let i=0;i<dots;i++)rect(x,'#f3ca67',108+i*4,77,2,8);rect(x,'#f4edc7',111,93,25,3)}
    else if(scene==='phone'){rect(x,'#2b2b42',0,0,240,160);rect(x,'#151625',68,8,104,144);rect(x,'#d8e9c4',74,17,92,126);rect(x,'#5a6378',79,25,82,12);for(let i=0;i<4;i++){rect(x,'#fff',80,43+i*22,80,17);rect(x,['#e56b88','#65c3bd','#f3ca67','#75a765'][i],84,47+i*22,9,9)}rect(x,'#65c3bd',104,132,31,4)}
    else if(scene==='card'){rect(x,'#8c5e5b',0,0,240,160);rect(x,'#5b3f49',0,118,240,42);rect(x,'#f8f0c8',45,25,150,96);rect(x,'#e56b88',45,25,150,14);for(let i=0;i<4;i++)rect(x,'#636579',62,53+i*14,105,2);rect(x,'#65c3bd',159,94,20,14)}
    else {rect(x,'#444563',0,0,240,160);rect(x,'#25263a',0,110,240,50);rect(x,'#9f6a78',18,53,75,57);rect(x,'#f8f0c8',24,61,63,24);rect(x,'#34364f',145,26,68,84);for(let i=0;i<3;i++)rect(x,'#c7b76d',153+i*18,39,12,12);party.forEach((p,i)=>drawMini(x,p,24+i*(party.length===4?44:64),108,f,'idle',2))}
  }
  setInterval(()=>{const value=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('.phone-now').forEach(el=>el.textContent=value)},30000);
  render();
}
